/**
 * Demo government services — ManualDemo only.
 * Never present as live PVOG/Bundesportal data.
 */
import type { GovService } from '@/lib/govdata/serviceTypes';

const DEMO_UPDATED = '2026-03-01';

export const MOCK_GOV_SERVICES: GovService[] = [
  // —— Private ——
  {
    serviceId: 'demo-ummeldung',
    title: 'Wohnsitz anmelden / Ummeldung',
    shortDescription: 'Anmeldung eines neuen Wohnsitzes beim Bürgerbüro der Zielkommune.',
    category: 'Wohnen',
    situationType: 'private',
    lifeSituation: 'Umzug',
    prerequisites: ['Personalausweis oder Reisepass', 'Wohnungsgeberbestätigung'],
    requiredDocuments: ['Ausweisdokument', 'Wohnungsgeberbestätigung', 'ggf. Heiratsurkunde bei Namensänderung'],
    responsibleAuthority: 'Bürgerbüro / Einwohnermeldeamt',
    regionRequired: true,
    regionHint: 'Zuständig ist die Kommune des neuen Wohnsitzes.',
    officialSourceUrl: 'https://www.bundesportal.de',
    sourceSystem: 'ManualDemo',
    lastUpdated: DEMO_UPDATED,
    confidence: 'high',
    matchKeywords: ['umzug', 'ummeldung', 'wohnsitz', 'anmeld', 'ziehe um', 'neue wohnung', 'bürgerbüro'],
  },
  {
    serviceId: 'demo-wohngeld',
    title: 'Wohngeld prüfen',
    shortDescription: 'Orientierung zu Wohngeld — Einkommen, Miete und Haushalt können relevant sein.',
    category: 'Wohnen',
    situationType: 'private',
    lifeSituation: 'Wohnkosten / niedriges Einkommen',
    prerequisites: ['Mietvertrag', 'Einkommensnachweise'],
    requiredDocuments: ['Mietvertrag', 'Einkommensnachweise', 'Kontoauszüge', 'Personalausweis'],
    responsibleAuthority: 'Wohngeldstelle der Kommune',
    regionRequired: true,
    regionHint: 'Zuständigkeit nach Wohnsitz — Fristen und Unterlagen variieren.',
    officialSourceUrl: 'https://www.bundesportal.de',
    sourceSystem: 'ManualDemo',
    lastUpdated: DEMO_UPDATED,
    confidence: 'medium',
    matchKeywords: ['wohngeld', 'miete', 'einkommen niedrig', 'unterstützung miete', 'alleinerziehend'],
  },
  {
    serviceId: 'demo-elterngeld',
    title: 'Elterngeld',
    shortDescription: 'Informationen zu Elterngeld nach Geburt — Antrag über zuständige Stelle.',
    category: 'Familie',
    situationType: 'private',
    lifeSituation: 'Geburt / Elternzeit',
    requiredDocuments: ['Geburtsurkunde', 'Einkommensnachweise', 'Personalausweis'],
    responsibleAuthority: 'Elterngeldstelle (Land / Kommune)',
    regionRequired: true,
    officialSourceUrl: 'https://www.bundesportal.de',
    sourceSystem: 'ManualDemo',
    lastUpdated: DEMO_UPDATED,
    confidence: 'high',
    matchKeywords: ['elterngeld', 'baby', 'geburt', 'kind bekommen', 'elternzeit'],
  },
  {
    serviceId: 'demo-kindergeld',
    title: 'Kindergeld',
    shortDescription: 'Kindergeld über Familienkasse — oft parallel zu anderen Familienleistungen.',
    category: 'Familie',
    situationType: 'private',
    lifeSituation: 'Kinder im Haushalt',
    requiredDocuments: ['Geburtsurkunde des Kindes', 'Steuer-ID', 'Kontoverbindung'],
    responsibleAuthority: 'Familienkasse',
    officialSourceUrl: 'https://www.arbeitsagentur.de/familie-und-kinder',
    sourceSystem: 'ManualDemo',
    lastUpdated: DEMO_UPDATED,
    confidence: 'high',
    matchKeywords: ['kindergeld', 'kinder', 'kind', 'familienkasse', 'schule'],
  },
  {
    serviceId: 'demo-pflege',
    title: 'Pflegegrad / Pflegeleistungen',
    shortDescription: 'Orientierung zu Pflegeversicherung, Pflegegrad und Leistungen.',
    category: 'Gesundheit & Pflege',
    situationType: 'private',
    lifeSituation: 'Pflegebedürftigkeit',
    requiredDocuments: ['Antrag Pflegekasse', 'Arztberichte', 'Personalausweis'],
    responsibleAuthority: 'Pflegekasse / MDK',
    officialSourceUrl: 'https://www.bundesportal.de',
    sourceSystem: 'ManualDemo',
    lastUpdated: DEMO_UPDATED,
    confidence: 'medium',
    matchKeywords: ['pflege', 'pflegebedürftig', 'pflegegrad', 'eltern pflege', 'mdk'],
  },
  {
    serviceId: 'demo-schwerbehinderung',
    title: 'Schwerbehindertenausweis',
    shortDescription: 'Antrag auf Feststellung der Behinderung beim Versorgungsamt.',
    category: 'Gesundheit & Pflege',
    situationType: 'private',
    requiredDocuments: ['Ärztliche Gutachten', 'Antragsformular', 'Personalausweis'],
    responsibleAuthority: 'Versorgungsamt',
    sourceSystem: 'ManualDemo',
    lastUpdated: DEMO_UPDATED,
    confidence: 'low',
    matchKeywords: ['schwerbehindert', 'behinderung', 'ausweis', 'gdB'],
  },
  {
    serviceId: 'demo-arbeitslos',
    title: 'Arbeitslosmeldung / Weiterbildung',
    shortDescription: 'Meldepflicht und Orientierung zu ALG I / Weiterbildung über Agentur für Arbeit.',
    category: 'Arbeit & Einkommen',
    situationType: 'private',
    requiredDocuments: ['Personalausweis', 'Arbeitsverträge', 'Kündigungsschreiben'],
    responsibleAuthority: 'Agentur für Arbeit / Jobcenter',
    officialSourceUrl: 'https://www.arbeitsagentur.de',
    sourceSystem: 'ManualDemo',
    lastUpdated: DEMO_UPDATED,
    confidence: 'medium',
    matchKeywords: ['arbeitslos', 'jobcenter', 'alg', 'weiterbildung', 'arbeitslosmeldung'],
  },
  {
    serviceId: 'demo-hilfe-lebensunterhalt',
    title: 'Hilfe zum Lebensunterhalt',
    shortDescription: 'Sozialhilfe bei fehlendem ausreichendem Einkommen — zuständiges Sozialamt prüfen.',
    category: 'Arbeit & Einkommen',
    situationType: 'private',
    requiredDocuments: ['Einkommensnachweise', 'Mietvertrag', 'Kontoauszüge'],
    responsibleAuthority: 'Sozialamt',
    regionRequired: true,
    sourceSystem: 'ManualDemo',
    lastUpdated: DEMO_UPDATED,
    confidence: 'medium',
    matchKeywords: ['sozialamt', 'lebensunterhalt', 'hilfe', 'einkommen zu niedrig', 'bedürftig'],
  },
  {
    serviceId: 'demo-jugendamt',
    title: 'Jugendamt / Kinder & Jugend',
    shortDescription: 'Unterstützung bei Sorgerecht, Kindeswohl, Schulwechsel — Jugendamt der Kommune.',
    category: 'Familie',
    situationType: 'private',
    responsibleAuthority: 'Jugendamt',
    regionRequired: true,
    sourceSystem: 'ManualDemo',
    lastUpdated: DEMO_UPDATED,
    confidence: 'medium',
    matchKeywords: ['jugendamt', 'sorgerecht', 'schulwechsel', 'kinder', 'trennung'],
  },
  // —— Business ——
  {
    serviceId: 'demo-gewerbe',
    title: 'Gewerbe anmelden',
    shortDescription: 'Gewerbeanmeldung bei der zuständigen Gemeinde — vor Tätigkeitsbeginn.',
    category: 'Gründung & Gewerbe',
    situationType: 'business',
    businessSituation: 'Gewerbe starten',
    requiredDocuments: ['Personalausweis', 'Gewerbeanmeldung', 'ggf. Handwerkskarte'],
    responsibleAuthority: 'Gewerbeamt / Bürgerbüro',
    regionRequired: true,
    officialSourceUrl: 'https://www.bundesportal.de',
    sourceSystem: 'ManualDemo',
    lastUpdated: DEMO_UPDATED,
    confidence: 'high',
    matchKeywords: ['gewerbe', 'anmelden', 'selbstständig', 'gründen', 'unternehmen'],
  },
  {
    serviceId: 'demo-gruendung',
    title: 'Unternehmen gründen',
    shortDescription: 'Orientierung zu Rechtsform, Register, Steuern und Sozialversicherung.',
    category: 'Gründung & Gewerbe',
    situationType: 'business',
    businessSituation: 'Neugründung',
    requiredDocuments: ['Gesellschaftsvertrag', 'Notarunterlagen', 'Steuerliche Erfassung'],
    responsibleAuthority: 'IHK / Handelsregister / Finanzamt',
    sourceSystem: 'ManualDemo',
    lastUpdated: DEMO_UPDATED,
    confidence: 'medium',
    matchKeywords: ['gründung', 'gmbh', 'ug', 'unternehmen gründen', 'startup'],
  },
  {
    serviceId: 'demo-betriebsstaette',
    title: 'Betriebsstätte verlegen',
    shortDescription: 'Ummeldung Gewerbe / Betriebsstätte bei Verlagerung des Standorts.',
    category: 'Gründung & Gewerbe',
    situationType: 'business',
    requiredDocuments: ['Gewerbeanmeldung', 'Mietvertrag neue Betriebsstätte'],
    responsibleAuthority: 'Gewerbeamt',
    regionRequired: true,
    sourceSystem: 'ManualDemo',
    lastUpdated: DEMO_UPDATED,
    confidence: 'medium',
    matchKeywords: ['betriebsstätte', 'verlegen', 'standort', 'umzug firma'],
  },
  {
    serviceId: 'demo-mitarbeiter',
    title: 'Mitarbeiter einstellen',
    shortDescription: 'Meldepflichten: Sozialversicherung, Finanzamt, ggf. Minijob-Zentrale.',
    category: 'Gründung & Gewerbe',
    situationType: 'business',
    businessSituation: 'Erste Beschäftigung',
    requiredDocuments: ['Arbeitsvertrag', 'Meldung Sozialversicherung', 'Lohnsteueranmeldung'],
    responsibleAuthority: 'Finanzamt / Krankenkasse / Minijob-Zentrale',
    sourceSystem: 'ManualDemo',
    lastUpdated: DEMO_UPDATED,
    confidence: 'high',
    matchKeywords: ['mitarbeiter', 'einstellen', 'beschäftigung', 'lohn', 'personal'],
  },
  {
    serviceId: 'demo-foerdermittel',
    title: 'Fördermittel prüfen',
    shortDescription: 'Überblick zu KfW, IHK, Landes- und EU-Förderprogrammen — keine Garantie.',
    category: 'Förderung',
    situationType: 'business',
    sourceSystem: 'ManualDemo',
    lastUpdated: DEMO_UPDATED,
    confidence: 'low',
    matchKeywords: ['förderung', 'fördermittel', 'kfw', 'zuschuss'],
  },
  {
    serviceId: 'demo-gaststaette',
    title: 'Gaststättenerlaubnis',
    shortDescription: 'Erlaubnis nach § 12 GastG — bei Ausschank und Bewirtung erforderlich.',
    category: 'Genehmigungen',
    situationType: 'business',
    requiredDocuments: ['Führungszeugnis', 'Gesundheitszeugnis', 'Raumpläne'],
    responsibleAuthority: 'Ordnungsamt / Gewerbeamt',
    regionRequired: true,
    sourceSystem: 'ManualDemo',
    lastUpdated: DEMO_UPDATED,
    confidence: 'medium',
    matchKeywords: ['gaststätte', 'gastro', 'erlaubnis', 'ausschank'],
  },
  {
    serviceId: 'demo-handwerk',
    title: 'Handwerksrolle / Kammerpflicht',
    shortDescription: 'Prüfung der Kammerpflicht und Eintragung in die Handwerksrolle.',
    category: 'Gründung & Gewerbe',
    situationType: 'business',
    responsibleAuthority: 'Handwerkskammer',
    sourceSystem: 'ManualDemo',
    lastUpdated: DEMO_UPDATED,
    confidence: 'medium',
    matchKeywords: ['handwerk', 'handwerksrolle', 'kammer', 'meister'],
  },
  {
    serviceId: 'demo-steuernummer',
    title: 'Steuernummer / Finanzamt',
    shortDescription: 'Fragebogen zur steuerlichen Erfassung für Gewerbe und Freiberufler.',
    category: 'Steuern & Abgaben',
    situationType: 'business',
    requiredDocuments: ['Fragebogen steuerliche Erfassung', 'Ausweisdokument'],
    responsibleAuthority: 'Finanzamt',
    officialSourceUrl: 'https://www.elster.de',
    sourceSystem: 'ManualDemo',
    lastUpdated: DEMO_UPDATED,
    confidence: 'high',
    matchKeywords: ['steuernummer', 'finanzamt', 'steuer', 'umsatzsteuer', 'elster'],
  },
];

export function getMockGovService(id: string): GovService | undefined {
  return MOCK_GOV_SERVICES.find((s) => s.serviceId === id);
}
