/**
 * Wegweiser mastercase journey matrix — Kirkel demo MVP templates.
 */
import type { CivicJourneyId, CivicJourneyTemplate } from '@/lib/civic/civicJourneyTemplates';

const KIRKEL = 'Zuständigkeit für Kirkel, Saarland prüfen';

type Q = { id: string; du: string; sie: string; skip?: RegExp };

function q(id: string, du: string, sie: string, skip?: RegExp): Q {
  return { id, du, sie, skip };
}

function tpl(
  config: Omit<CivicJourneyTemplate, 'missingQuestionTemplates' | 'situationSummaryDu' | 'situationSummarySie' | 'quickStartText' | 'defaultMode' | 'knownContextUse'> & {
    missingQuestions: Q[];
    summaryDu: string;
    summarySie: string;
    quickStartText?: string;
    defaultMode?: 'private' | 'business' | 'unsure';
    knownContextUse?: string[];
  },
): CivicJourneyTemplate {
  const domain = config.domain;
  const defaultMode =
    config.defaultMode ?? (domain === 'business' ? 'business' : domain === 'private' ? 'private' : 'unsure');
  return {
    ...config,
    defaultMode,
    quickStartText:
      config.quickStartText ??
      `Ich brauche Orientierung zu „${config.title}“ in Kirkel — welche Schritte und Unterlagen sind wichtig?`,
    knownContextUse: config.knownContextUse ?? ['municipality', 'federalState', 'demo_profile'],
    missingQuestionTemplates: config.missingQuestions.map((m) => ({
      id: m.id,
      questionDu: m.du,
      questionSie: m.sie,
      skipIfTextMatches: m.skip,
    })),
    situationSummaryDu: config.summaryDu,
    situationSummarySie: config.summarySie,
  };
}

export const MASTERCASE_JOURNEY_MATRIX: CivicJourneyTemplate[] = [
  tpl({
    id: 'child_birth_kita',
    title: 'Geburt & Kita',
    domain: 'private',
    priority: 'mvp',
    triggerPhrases: [
      'bekomme ein kind',
      'geburt',
      'schwanger',
      'elterngeld',
      'kindergeld',
      'kita',
      'kinderbetreuung',
      'familienversicherung',
      'elternzeit',
      'baby',
    ],
    defaultMode: 'private',
    quickStartLabel: 'Geburt & Kita',
    quickStartText:
      'Ich bekomme ein Kind. An was muss ich alles denken? Welche Formulare und Behördengänge sind nötig?',
    knownContextUse: ['municipality', 'federalState', 'demo_profile'],
    topicLabels: ['Familie', 'Gesundheit', 'Kinderbetreuung'],
    orderedSteps: [
      'Vor der Geburt Krankenversicherung, Mutterschaftsleistungen und Elternzeit prüfen',
      'Geburt beim Standesamt Kirkel beurkunden lassen',
      'Geburtsurkunde für weitere Anträge nutzen',
      'Kindergeld bei der Familienkasse beantragen',
      'Elterngeld vorbereiten und einreichen',
      'Kita-Platz / Kinderbetreuung in Kirkel vormerken',
      'Unterlagen sammeln und offizielle Online-Informationen öffnen',
      KIRKEL,
    ],
    suggestedAuthorities: [
      'Standesamt Kirkel',
      'Familienkasse',
      'Elterngeldstelle',
      'Krankenkasse',
      'Kita / Kinderbetreuung',
      'Arbeitgeber (Elternzeit / Mutterschaftsgeld)',
    ],
    requiredDocuments: [
      'Ausweis',
      'Geburtsurkunde',
      'Steuer-ID',
      'Einkommensnachweise',
      'Krankenkassendaten',
      'Arbeitgeberbescheinigung',
    ],
    sourceKeywords: [
      'Elterngeld',
      'Kindergeld',
      'Kinderbetreuung',
      'Familienversicherung',
      'Geburt',
      'Standesamt',
      'Elternzeit',
    ],
    relevantServiceKeywords: ['elterngeld', 'kindergeld', 'kita', 'krankenversicherung', 'geburt'],
    catalogServiceIds: ['vc-elterngeld', 'vc-kindergeld', 'vc-kita'],
    uncataloguedStepLabels: ['Geburtsurkunde / Standesamt Kirkel'],
    missingQuestions: [
      q('born', 'Ist das Kind bereits geboren oder erwartest du es?', 'Ist das Kind bereits geboren oder erwarten Sie es?', /geboren|schwanger|erwarte/i),
      q('kita', 'Ab wann wird Betreuung benötigt?', 'Ab wann wird Betreuung benötigt?', /kita|betreuung/i),
      q('first', 'Geht es um das erste Kind?', 'Geht es um das erste Kind?', /erstes kind|geschwister/i),
      q('ins', 'Ist die Krankenversicherung bereits geklärt?', 'Ist die Krankenversicherung bereits geklärt?', /krankenkasse|krankenversichert/i),
    ],
    summaryDu: 'Du erwartest ein Kind und brauchst einen strukturierten Überblick zu Anträgen, Unterlagen und Stellen in Kirkel.',
    summarySie: 'Sie erwarten ein Kind und brauchen einen strukturierten Überblick zu Anträgen, Unterlagen und Stellen in Kirkel.',
  }),
  tpl({
    id: 'moving_with_children',
    title: 'Umzug mit Kindern',
    domain: 'private',
    priority: 'mvp',
    triggerPhrases: ['umzug mit kindern', 'ziehe mit kindern', 'ziehe mit', 'kindern um', 'schulwechsel', 'ummeld', 'umzug'],
    defaultMode: 'private',
    quickStartLabel: 'Umzug mit Kindern',
    quickStartText:
      'Ich ziehe mit Kindern um und brauche Orientierung zu Ummeldung, Schule und Unterstützung in Kirkel.',
    knownContextUse: ['municipality', 'federalState'],
    topicLabels: ['Wohnen', 'Familie', 'Schule'],
    orderedSteps: [
      'Umzugsrichtung klären (nach Kirkel, innerhalb Kirkel, aus Kirkel weg)',
      'Wohnsitz beim Bürgeramt Kirkel anmelden',
      'Schule und Betreuung prüfen',
      'Wohngeld prüfen, falls relevant',
      'Kindergeld-Adresse aktualisieren',
      'Fahrzeug ummelden, falls betroffen',
      KIRKEL,
    ],
    suggestedAuthorities: ['Bürgeramt Kirkel', 'Schule / Schulamt', 'Wohngeldstelle', 'Familienkasse'],
    requiredDocuments: ['Ausweis', 'Wohnungsgeberbestätigung', 'Mietvertrag', 'Meldebescheinigung'],
    sourceKeywords: ['ummeldung', 'umzug', 'wohngeld', 'schule', 'kindergeld'],
    relevantServiceKeywords: ['ummeld', 'umzug', 'wohngeld', 'schule'],
    catalogServiceIds: ['vc-ummeldung', 'vc-wohngeld', 'vc-kindergeld'],
    uncataloguedStepLabels: ['Schulwechsel / Schulamt'],
    missingQuestions: [
      q('dir', 'Ziehst du nach Kirkel, innerhalb Kirkel oder aus Kirkel weg?', 'Ziehen Sie nach Kirkel, innerhalb Kirkel oder aus Kirkel weg?', /nach kirkel|innerhalb|aus kirkel/i),
      q('kids', 'Sind Kinder betroffen?', 'Sind Kinder betroffen?', /kind|kinder|schule/i),
      q('car', 'Gibt es ein Fahrzeug, das umzumelden ist?', 'Gibt es ein Fahrzeug, das umzumelden ist?', /fahrzeug|auto|kfz/i),
    ],
    summaryDu: 'Du planst einen Umzug mit Kindern und brauchst einen Behördenfahrplan für Kirkel.',
    summarySie: 'Sie planen einen Umzug mit Kindern und brauchen einen Behördenfahrplan für Kirkel.',
  }),
  tpl({
    id: 'housing_support',
    title: 'Wohngeld & Unterstützung',
    domain: 'private',
    priority: 'mvp',
    triggerPhrases: ['wohngeld', 'wohnkosten', 'miete hoch', 'unterstützung wohnen', 'sozialhilfe wohnen'],
    defaultMode: 'private',
    quickStartLabel: 'Wohngeld & Unterstützung',
    quickStartText: 'Meine Wohnkosten sind hoch — ich möchte prüfen, ob Wohngeld oder andere Unterstützung in Frage kommt.',
    knownContextUse: ['municipality'],
    topicLabels: ['Wohnen', 'Soziales'],
    orderedSteps: ['Wohnsituation prüfen', 'Einkommen und Haushalt zusammenstellen', 'Wohngeld-Antrag vorbereiten', 'Weitere Leistungen prüfen', KIRKEL],
    suggestedAuthorities: ['Wohngeldstelle', 'Sozialamt Kirkel'],
    requiredDocuments: ['Mietvertrag', 'Einkommensnachweise', 'Kontoauszüge', 'Ausweis'],
    sourceKeywords: ['wohngeld', 'miete', 'wohnen'],
    relevantServiceKeywords: ['wohngeld', 'miete'],
    catalogServiceIds: ['vc-wohngeld'],
    uncataloguedStepLabels: [],
    missingQuestions: [q('hh', 'Wie viele Personen leben im Haushalt?', 'Wie viele Personen leben im Haushalt?', /haushalt|personen/i)],
    summaryDu: 'Du möchtest Wohngeld oder Unterstützung für deine Wohnsituation in Kirkel prüfen.',
    summarySie: 'Sie möchten Wohngeld oder Unterstützung für Ihre Wohnsituation in Kirkel prüfen.',
  }),
  tpl({
    id: 'childcare_school',
    title: 'Kita & Schule',
    domain: 'private',
    priority: 'mvp',
    triggerPhrases: ['kita platz', 'schulanmeldung', 'schule anmelden', 'hort', 'betreuung schule'],
    defaultMode: 'private',
    knownContextUse: ['municipality'],
    topicLabels: ['Kinderbetreuung', 'Schule'],
    orderedSteps: ['Betreuungs- oder Schulbedarf klären', 'Anmeldung bei Kommune/Schule vorbereiten', 'Unterlagen sammeln', KIRKEL],
    suggestedAuthorities: ['Kommune Kirkel', 'Schule', 'Jugendamt'],
    requiredDocuments: ['Ausweis', 'Meldebescheinigung', 'Impfpass / Gesundheitsnachweise'],
    sourceKeywords: ['kita', 'schule', 'kinderbetreuung'],
    relevantServiceKeywords: ['kita', 'schule'],
    catalogServiceIds: ['vc-kita'],
    uncataloguedStepLabels: ['Schulanmeldung'],
    missingQuestions: [q('age', 'Welches Alter hat das Kind?', 'Welches Alter hat das Kind?', /\d+\s*jahre|kleinkind|schulkind/i)],
    summaryDu: 'Du brauchst Orientierung zu Kita- oder Schulanmeldung in Kirkel.',
    summarySie: 'Sie brauchen Orientierung zu Kita- oder Schulanmeldung in Kirkel.',
  }),
  tpl({
    id: 'family_care',
    title: 'Pflegefall',
    domain: 'private',
    priority: 'mvp',
    triggerPhrases: ['pflegefall', 'pflegegrad', 'pflegekasse', 'angehörige pflege', 'pflegebedürftig'],
    defaultMode: 'private',
    quickStartLabel: 'Pflegefall',
    quickStartText: 'In meiner Familie gibt es einen Pflegefall. Welche Leistungen und Stellen sind relevant?',
    knownContextUse: ['municipality'],
    topicLabels: ['Pflege', 'Familie'],
    orderedSteps: ['Pflegebedarf einordnen', 'Pflegegrad-Antrag vorbereiten', 'Beratung nutzen', 'Leistungen prüfen', KIRKEL],
    suggestedAuthorities: ['Pflegekasse', 'Pflegestützpunkt', 'Sozialamt Kirkel'],
    requiredDocuments: ['Versichertennachweis', 'Atteste', 'Antragsformulare'],
    sourceKeywords: ['pflege', 'pflegegrad', 'pflegekasse'],
    relevantServiceKeywords: ['pflege', 'pflegegrad'],
    catalogServiceIds: ['vc-pflege'],
    uncataloguedStepLabels: ['Pflegestützpunkt vor Ort'],
    missingQuestions: [
      q('home', 'Wird zu Hause oder in einer Einrichtung gepflegt?', 'Wird zu Hause oder in einer Einrichtung gepflegt?', /zu hause|heim|einrichtung/i),
      q('grade', 'Liegt bereits ein Pflegegrad vor?', 'Liegt bereits ein Pflegegrad vor?', /pflegegrad|mdk/i),
    ],
    summaryDu: 'Du begleitest einen Pflegefall und suchst Orientierung zu Leistungen in Kirkel.',
    summarySie: 'Sie begleiten einen Pflegefall und suchen Orientierung zu Leistungen in Kirkel.',
  }),
  tpl({
    id: 'id_passport',
    title: 'Reisepass & Ausweis',
    domain: 'private',
    priority: 'mvp',
    triggerPhrases: ['reisepass', 'personalausweis', 'ausweis beantragen', 'pass beantragen'],
    defaultMode: 'private',
    quickStartLabel: 'Reisepass & Ausweis',
    quickStartText: 'Ich brauche einen neuen Reisepass oder Personalausweis — welche Unterlagen brauche ich beim Bürgeramt?',
    knownContextUse: ['municipality'],
    topicLabels: ['Ausweis', 'Meldeamt'],
    orderedSteps: ['Termin beim Bürgeramt Kirkel', 'Biometrisches Foto vorbereiten', 'Antrag stellen', 'Abholung planen'],
    suggestedAuthorities: ['Bürgeramt Kirkel'],
    requiredDocuments: ['Biometrisches Passfoto', 'Alter Ausweis/Reisepass', 'Geburtsurkunde falls nötig'],
    sourceKeywords: ['reisepass', 'personalausweis', 'ausweis'],
    relevantServiceKeywords: ['reisepass', 'personalausweis'],
    catalogServiceIds: ['vc-ummeldung'],
    uncataloguedStepLabels: ['Reisepass / Personalausweis — Bürgeramt'],
    missingQuestions: [q('type', 'Reisepass, Personalausweis oder beides?', 'Reisepass, Personalausweis oder beides?', /reisepass|personalausweis/i)],
    summaryDu: 'Du möchtest Reisepass oder Personalausweis in Kirkel beantragen.',
    summarySie: 'Sie möchten Reisepass oder Personalausweis in Kirkel beantragen.',
  }),
  tpl({
    id: 'separation_support',
    title: 'Trennung & Unterhalt',
    domain: 'private',
    priority: 'mvp',
    triggerPhrases: ['trennung', 'scheidung', 'unterhalt', 'sorgerecht'],
    defaultMode: 'private',
    topicLabels: ['Familie'],
    orderedSteps: ['Situation und Kinder klären', 'Beratungsstellen nutzen', 'Unterlagen sammeln', KIRKEL],
    suggestedAuthorities: ['Jugendamt', 'Beratungsstelle', 'Familiengericht (Orientierung)'],
    requiredDocuments: ['Einkommensnachweise', 'Verträge', 'Schreiben'],
    sourceKeywords: ['unterhalt', 'sorgerecht', 'trennung'],
    relevantServiceKeywords: ['unterhalt', 'familie'],
    catalogServiceIds: [],
    uncataloguedStepLabels: ['Familienberatung'],
    missingQuestions: [q('kids', 'Sind Kinder betroffen?', 'Sind Kinder betroffen?', /kind|kinder/i)],
    summaryDu: 'Du befindest dich in einer Trennungssituation und suchst Orientierung zu Anlaufstellen.',
    summarySie: 'Sie befinden sich in einer Trennungssituation und suchen Orientierung zu Anlaufstellen.',
  }),
  tpl({
    id: 'unemployment_training',
    title: 'Arbeitslosigkeit & Weiterbildung',
    domain: 'private',
    priority: 'mvp',
    triggerPhrases: ['arbeitslos', 'jobcenter', 'alg', 'weiterbildung', 'arbeitslosengeld'],
    defaultMode: 'private',
    topicLabels: ['Arbeit', 'Soziales'],
    orderedSteps: ['Arbeitslosmeldung vorbereiten', 'Leistungen beim Jobcenter prüfen', 'Weiterbildung klären', KIRKEL],
    suggestedAuthorities: ['Jobcenter', 'Arbeitsagentur'],
    requiredDocuments: ['Ausweis', 'Arbeitsverträge', 'Kündigung', 'Kontoauszüge'],
    sourceKeywords: ['arbeitslos', 'alg', 'weiterbildung'],
    relevantServiceKeywords: ['arbeitslos', 'alg'],
    catalogServiceIds: ['vc-arbeitslos'],
    uncataloguedStepLabels: [],
    missingQuestions: [q('when', 'Seit wann bist du arbeitslos?', 'Seit wann sind Sie arbeitslos?', /seit|woche|monat/i)],
    summaryDu: 'Du bist arbeitslos geworden und brauchst Orientierung zu Meldungen und Leistungen.',
    summarySie: 'Sie sind arbeitslos geworden und brauchen Orientierung zu Meldungen und Leistungen.',
  }),
  tpl({
    id: 'pension_retirement',
    title: 'Rente & Ruhestand',
    domain: 'private',
    priority: 'mvp',
    triggerPhrases: ['rente', 'ruhestand', 'rentenantrag', 'rentenversicherung'],
    defaultMode: 'private',
    topicLabels: ['Rente'],
    orderedSteps: ['Renteninformation prüfen', 'Rentenantrag vorbereiten', 'Versicherungen im Ruhestand klären', KIRKEL],
    suggestedAuthorities: ['Deutsche Rentenversicherung', 'Krankenkasse'],
    requiredDocuments: ['Versicherungsverlauf', 'Ausweis', 'Bescheide'],
    sourceKeywords: ['rente', 'ruhestand'],
    relevantServiceKeywords: ['rente'],
    catalogServiceIds: [],
    uncataloguedStepLabels: ['Rentenberatung'],
    missingQuestions: [q('when', 'Wann ist der geplante Rentenbeginn?', 'Wann ist der geplante Rentenbeginn?', /ab \d|jahr|monat/i)],
    summaryDu: 'Du planst den Ruhestand und brauchst einen Überblick zum Rentenantrag.',
    summarySie: 'Sie planen den Ruhestand und brauchen einen Überblick zum Rentenantrag.',
  }),
  tpl({
    id: 'death_case',
    title: 'Todesfall',
    domain: 'private',
    priority: 'mvp',
    triggerPhrases: ['todesfall', 'sterbefall', 'beerdigung', 'erbschaft'],
    defaultMode: 'private',
    topicLabels: ['Familie', 'Standesamt'],
    orderedSteps: ['Sterbeurkunde beim Standesamt', 'Behörden und Versicherungen informieren', 'Nachlass/Erbschaft klären', KIRKEL],
    suggestedAuthorities: ['Standesamt Kirkel', 'Versicherungen', 'Nachlassgericht (Orientierung)'],
    requiredDocuments: ['Sterbeurkunde', 'Ausweis', 'Testament falls vorhanden'],
    sourceKeywords: ['sterbefall', 'standesamt', 'erbschaft'],
    relevantServiceKeywords: ['sterbefall'],
    catalogServiceIds: [],
    uncataloguedStepLabels: ['Bestattung / Sterbeurkunde'],
    missingQuestions: [q('rel', 'Gibt es Angehörige oder ein Testament?', 'Gibt es Angehörige oder ein Testament?', /angehörige|testament|erbe/i)],
    summaryDu: 'Nach einem Todesfall brauchst du Orientierung zu Behördenwegen und Unterlagen.',
    summarySie: 'Nach einem Todesfall brauchen Sie Orientierung zu Behördenwegen und Unterlagen.',
  }),
  tpl({
    id: 'marriage_name_change',
    title: 'Heirat & Namensänderung',
    domain: 'private',
    priority: 'mvp',
    triggerPhrases: ['heirat', 'hochzeit', 'namensänderung', 'eheschließung', 'standesamt heirat'],
    defaultMode: 'private',
    topicLabels: ['Familie', 'Standesamt'],
    orderedSteps: ['Eheschließung beim Standesamt vorbereiten', 'Namensänderung prüfen', 'Meldedaten aktualisieren', KIRKEL],
    suggestedAuthorities: ['Standesamt Kirkel', 'Bürgeramt'],
    requiredDocuments: ['Ausweis', 'Geburtsurkunde', 'Ledigkeitsbescheinigung'],
    sourceKeywords: ['heirat', 'namensänderung', 'standesamt'],
    relevantServiceKeywords: ['heirat', 'standesamt'],
    catalogServiceIds: [],
    uncataloguedStepLabels: ['Eheschließung Standesamt'],
    missingQuestions: [q('name', 'Ist eine Namensänderung geplant?', 'Ist eine Namensänderung geplant?', /namensänderung|name ändern/i)],
    summaryDu: 'Du planst eine Heirat oder Namensänderung in Kirkel.',
    summarySie: 'Sie planen eine Heirat oder Namensänderung in Kirkel.',
  }),
  tpl({
    id: 'vehicle_registration',
    title: 'Fahrzeug & Zulassung',
    domain: 'private',
    priority: 'mvp',
    triggerPhrases: ['kfz', 'fahrzeug anmelden', 'zulassung', 'auto ummelden', 'kennzeichen'],
    defaultMode: 'private',
    topicLabels: ['Mobilität'],
    orderedSteps: ['Zulassungsstelle Termin', 'Versicherung und Unterlagen prüfen', 'Fahrzeug an- oder ummelden', KIRKEL],
    suggestedAuthorities: ['Zulassungsstelle', 'Versicherung'],
    requiredDocuments: ['Fahrzeugbrief', 'Ausweis', 'Versicherungsnachweis', 'TÜV-Bescheinigung'],
    sourceKeywords: ['kfz', 'zulassung', 'fahrzeug'],
    relevantServiceKeywords: ['kfz', 'zulassung'],
    catalogServiceIds: [],
    uncataloguedStepLabels: ['Kfz-Zulassung'],
    missingQuestions: [q('new', 'Neuanschaffung oder Ummeldung?', 'Neuanschaffung oder Ummeldung?', /neu|ummeld|gebraucht/i)],
    summaryDu: 'Du musst ein Fahrzeug anmelden oder ummelden.',
    summarySie: 'Sie müssen ein Fahrzeug anmelden oder ummelden.',
  }),
  tpl({
    id: 'business_registration',
    title: 'Gewerbe anmelden',
    domain: 'business',
    priority: 'mvp',
    triggerPhrases: ['gewerbe anmelden', 'gewerbeanmeldung', 'selbstständig machen', 'unternehmen gründen'],
    defaultMode: 'business',
    quickStartLabel: 'Gewerbe anmelden',
    quickStartText: 'Ich möchte ein Gewerbe in Kirkel anmelden und brauche einen Überblick über Gewerbeamt, Finanzamt und IHK.',
    knownContextUse: ['municipality'],
    topicLabels: ['Gewerbe', 'Gründung'],
    orderedSteps: ['Tätigkeit und Rechtsform klären', 'Gewerbeamt Kirkel', 'Finanzamt', 'IHK/HWK', 'Berufsgenossenschaft', KIRKEL],
    suggestedAuthorities: ['Gewerbeamt Kirkel', 'Finanzamt', 'IHK', 'Berufsgenossenschaft'],
    requiredDocuments: ['Ausweis', 'Gewerbeanmeldung', 'Handwerkskarte falls nötig'],
    sourceKeywords: ['gewerbe', 'gründung', 'finanzamt', 'ihk'],
    relevantServiceKeywords: ['gewerbe', 'gründ', 'finanzamt'],
    catalogServiceIds: ['vc-gewerbe', 'vc-gruendung', 'vc-finanzamt', 'vc-kammer', 'vc-bg'],
    uncataloguedStepLabels: [],
    missingQuestions: [
      q('act', 'Welche Tätigkeit soll angemeldet werden?', 'Welche Tätigkeit soll angemeldet werden?', /tätigkeit|handwerk|handel/i),
      q('form', 'Einzelunternehmen oder Gesellschaft?', 'Einzelunternehmen oder Gesellschaft?', /einzelunternehmen|gmbh|ug/i),
      q('lic', 'Gibt es erlaubnispflichtige Anteile?', 'Gibt es erlaubnispflichtige Anteile?', /erlaubnis|gaststätte/i),
      q('emp', 'Wird Personal eingestellt?', 'Wird Personal eingestellt?', /mitarbeiter|personal/i),
    ],
    summaryDu: 'Du möchtest ein Gewerbe in Kirkel anmelden.',
    summarySie: 'Sie möchten ein Gewerbe in Kirkel anmelden.',
  }),
  tpl({
    id: 'self_employed_start',
    title: 'Selbstständigkeit starten',
    domain: 'business',
    priority: 'mvp',
    triggerPhrases: ['selbstständig', 'freiberufler', 'freelance', 'einzelfirma'],
    defaultMode: 'business',
    topicLabels: ['Selbstständigkeit'],
    orderedSteps: ['Tätigkeit einordnen', 'Gewerbe oder Freiberuf klären', 'Steuer und Sozialversicherung', KIRKEL],
    suggestedAuthorities: ['Finanzamt', 'Gewerbeamt Kirkel', 'Krankenkasse'],
    requiredDocuments: ['Ausweis', 'Businessplan', 'Steuer-ID'],
    sourceKeywords: ['selbstständig', 'freiberuf', 'gewerbe'],
    relevantServiceKeywords: ['selbstständig', 'freiberuf'],
    catalogServiceIds: ['vc-gewerbe', 'vc-finanzamt'],
    uncataloguedStepLabels: [],
    missingQuestions: [q('type', 'Freiberuf oder Gewerbe?', 'Freiberuf oder Gewerbe?', /freiberuf|gewerbe/i)],
    summaryDu: 'Du startest eine Selbstständigkeit in Kirkel.',
    summarySie: 'Sie starten eine Selbstständigkeit in Kirkel.',
  }),
  tpl({
    id: 'company_foundation',
    title: 'Gesellschaft gründen',
    domain: 'business',
    priority: 'mvp',
    triggerPhrases: ['gmbh gründen', 'ug gründen', 'gesellschaft gründen', 'notar gründung'],
    defaultMode: 'business',
    topicLabels: ['Gründung'],
    orderedSteps: ['Rechtsform wählen', 'Notar und Gesellschaftsvertrag', 'Handelsregister', 'Gewerbe und Finanzamt', KIRKEL],
    suggestedAuthorities: ['Notar', 'Handelsregister', 'Gewerbeamt', 'Finanzamt'],
    requiredDocuments: ['Gesellschaftsvertrag', 'Ausweis', 'Stammkapital-Nachweis'],
    sourceKeywords: ['gmbh', 'ug', 'handelsregister', 'gründung'],
    relevantServiceKeywords: ['gmbh', 'gründung'],
    catalogServiceIds: ['vc-gruendung', 'vc-finanzamt'],
    uncataloguedStepLabels: ['Notar / Handelsregister'],
    missingQuestions: [q('form', 'GmbH, UG oder andere Form?', 'GmbH, UG oder andere Form?', /gmbh|ug|ag/i)],
    summaryDu: 'Du planst die Gründung einer Gesellschaft.',
    summarySie: 'Sie planen die Gründung einer Gesellschaft.',
  }),
  tpl({
    id: 'employer_onboarding',
    title: 'Arbeitgeber werden',
    domain: 'business',
    priority: 'mvp',
    triggerPhrases: ['arbeitgeber', 'mitarbeitende', 'mitarbeiter einstellen', 'erste mitarbeiter', 'personal einstellen'],
    defaultMode: 'business',
    quickStartLabel: 'Arbeitgeber werden',
    quickStartText: 'Ich stelle zum ersten Mal Mitarbeitende ein und brauche einen Überblick über Meldungen und Pflichten.',
    topicLabels: ['Arbeit'],
    orderedSteps: ['Betriebsnummer klären', 'Sozialversicherungsmeldungen', 'Lohnabrechnung', 'Berufsgenossenschaft', KIRKEL],
    suggestedAuthorities: ['Finanzamt', 'Krankenkasse', 'Berufsgenossenschaft', 'IHK'],
    requiredDocuments: ['Arbeitsverträge', 'SV-Meldungen', 'Lohnunterlagen'],
    sourceKeywords: ['arbeitgeber', 'personal', 'sozialversicherung'],
    relevantServiceKeywords: ['arbeitgeber', 'personal'],
    catalogServiceIds: ['vc-personal', 'vc-bg', 'vc-finanzamt'],
    uncataloguedStepLabels: [],
    missingQuestions: [
      q('count', 'Wie viele Mitarbeitende?', 'Wie viele Mitarbeitende?', /mitarbeiter|\d+/i),
      q('type', 'Vollzeit, Teilzeit oder Minijob?', 'Vollzeit, Teilzeit oder Minijob?', /vollzeit|teilzeit|minijob/i),
    ],
    summaryDu: 'Du wirst Arbeitgeber und brauchst eine Übersicht der Pflichten.',
    summarySie: 'Sie werden Arbeitgeber und brauchen eine Übersicht der Pflichten.',
  }),
  tpl({
    id: 'craft_business_start',
    title: 'Handwerksbetrieb starten',
    domain: 'business',
    priority: 'mvp',
    triggerPhrases: ['handwerk', 'handwerkskammer', 'meister', 'handwerksbetrieb'],
    defaultMode: 'business',
    topicLabels: ['Handwerk'],
    orderedSteps: ['Meisterpflicht prüfen', 'Handwerkskammer', 'Gewerbeamt', KIRKEL],
    suggestedAuthorities: ['Handwerkskammer', 'Gewerbeamt Kirkel', 'Finanzamt'],
    requiredDocuments: ['Meisterbrief', 'Ausweis', 'Gewerbeanmeldung'],
    sourceKeywords: ['handwerk', 'handwerkskammer'],
    relevantServiceKeywords: ['handwerk'],
    catalogServiceIds: ['vc-gewerbe', 'vc-kammer'],
    uncataloguedStepLabels: [],
    missingQuestions: [q('trade', 'Welches Handwerk?', 'Welches Handwerk?', /handwerk|elektriker|maler/i)],
    summaryDu: 'Du startest einen Handwerksbetrieb in Kirkel.',
    summarySie: 'Sie starten einen Handwerksbetrieb in Kirkel.',
  }),
  tpl({
    id: 'gastronomy_permit',
    title: 'Gastronomie & Erlaubnis',
    domain: 'business',
    priority: 'mvp',
    triggerPhrases: ['gaststätte', 'gastronomie', 'schankerlaubnis', 'gastgewerbe', 'restaurant eröffnen'],
    defaultMode: 'business',
    topicLabels: ['Gastronomie', 'Erlaubnis'],
    orderedSteps: ['Erlaubnispflicht klären', 'Gewerbe- und gaststättenrechtliche Anforderungen', 'Behörden Kirkel', KIRKEL],
    suggestedAuthorities: ['Gewerbeamt Kirkel', 'Ordnungsamt', 'Finanzamt'],
    requiredDocuments: ['Konzept', 'Hygieneunterlagen', 'Gewerbeanmeldung'],
    sourceKeywords: ['gaststätte', 'gastronomie', 'erlaubnis'],
    relevantServiceKeywords: ['gaststätte', 'erlaubnis'],
    catalogServiceIds: ['vc-gewerbe', 'vc-finanzamt'],
    uncataloguedStepLabels: ['Gaststättenerlaubnis'],
    missingQuestions: [q('alc', 'Wird Alkohol ausgeschenkt?', 'Wird Alkohol ausgeschenkt?', /alkohol|schank|bier|wein/i)],
    summaryDu: 'Du planst eine Gastronomie mit erlaubnispflichtigen Anteilen in Kirkel.',
    summarySie: 'Sie planen eine Gastronomie mit erlaubnispflichtigen Anteilen in Kirkel.',
  }),
  tpl({
    id: 'business_change_deregister',
    title: 'Gewerbe ummelden / abmelden',
    domain: 'business',
    priority: 'mvp',
    triggerPhrases: ['gewerbe abmelden', 'gewerbe ummelden', 'betrieb schließen'],
    defaultMode: 'business',
    topicLabels: ['Gewerbe'],
    orderedSteps: ['Art der Änderung klären', 'Gewerbeamt informieren', 'Finanzamt und SV', KIRKEL],
    suggestedAuthorities: ['Gewerbeamt Kirkel', 'Finanzamt', 'IHK'],
    requiredDocuments: ['Gewerbeschein', 'Schlussbilanz falls relevant'],
    sourceKeywords: ['gewerbe abmelden', 'ummeld'],
    relevantServiceKeywords: ['gewerbe', 'abmeld'],
    catalogServiceIds: ['vc-gewerbe', 'vc-finanzamt'],
    uncataloguedStepLabels: [],
    missingQuestions: [q('ch', 'Ummeldung, Abmeldung oder Tätigkeitsänderung?', 'Ummeldung, Abmeldung oder Tätigkeitsänderung?', /ummeld|abmeld/i)],
    summaryDu: 'Du musst ein Gewerbe ummelden oder abmelden.',
    summarySie: 'Sie müssen ein Gewerbe ummelden oder abmelden.',
  }),
  tpl({
    id: 'funding_startup',
    title: 'Fördermittel & Gründungsstart',
    domain: 'business',
    priority: 'mvp',
    triggerPhrases: ['förderung', 'fördermittel', 'gründungszuschuss', 'existenzgründung'],
    defaultMode: 'business',
    topicLabels: ['Förderung'],
    orderedSteps: ['Finanzbedarf skizzieren', 'Förderprogramme prüfen', 'Gewerbeanmeldung vorbereiten', KIRKEL],
    suggestedAuthorities: ['IHK', 'Förderstelle', 'Gewerbeamt Kirkel'],
    requiredDocuments: ['Businessplan', 'Finanzplan', 'Antragsunterlagen'],
    sourceKeywords: ['förderung', 'gründung', 'existenzgründ'],
    relevantServiceKeywords: ['förderung', 'gründung'],
    catalogServiceIds: ['vc-foerderung', 'vc-gruendung'],
    uncataloguedStepLabels: ['Regionale Wirtschaftsförderung'],
    missingQuestions: [q('goal', 'Startkapital, Beratung oder beides?', 'Startkapital, Beratung oder beides?', /kapital|beratung/i)],
    summaryDu: 'Du suchst Fördermittel für deinen Gründungsstart in der Region.',
    summarySie: 'Sie suchen Fördermittel für Ihren Gründungsstart in der Region.',
  }),
  tpl({
    id: 'building_use_change',
    title: 'Nutzungsänderung Gebäude',
    domain: 'business',
    priority: 'mvp',
    triggerPhrases: ['nutzungsänderung', 'bauantrag', 'gewerbe im wohnhaus', 'bauordnung'],
    defaultMode: 'business',
    topicLabels: ['Bauen', 'Gewerbe'],
    orderedSteps: ['Nutzung prüfen', 'Bauordnung und Genehmigung', 'Gewerbeamt', KIRKEL],
    suggestedAuthorities: ['Bauamt', 'Gewerbeamt Kirkel', 'Ordnungsamt'],
    requiredDocuments: ['Grundriss', 'Nutzungskonzept', 'Eigentumsnachweis'],
    sourceKeywords: ['bauantrag', 'nutzungsänderung'],
    relevantServiceKeywords: ['bau', 'nutzung'],
    catalogServiceIds: [],
    uncataloguedStepLabels: ['Bauamt / Genehmigung'],
    missingQuestions: [q('use', 'Welche Nutzung ist geplant?', 'Welche Nutzung ist geplant?', /gewerbe|wohnen|lager/i)],
    summaryDu: 'Du planst eine Nutzungsänderung für ein Gebäude in Kirkel.',
    summarySie: 'Sie planen eine Nutzungsänderung für ein Gebäude in Kirkel.',
  }),
  tpl({
    id: 'event_special_use',
    title: 'Veranstaltung & Sondernutzung',
    domain: 'business',
    priority: 'mvp',
    triggerPhrases: ['veranstaltung', 'sondernutzung', 'straße sperren', 'event genehmigung'],
    defaultMode: 'business',
    topicLabels: ['Veranstaltung'],
    orderedSteps: ['Art der Veranstaltung klären', 'Genehmigungen prüfen', 'Ordnungsamt', KIRKEL],
    suggestedAuthorities: ['Ordnungsamt Kirkel', 'Polizei (Orientierung)', 'Gewerbeamt'],
    requiredDocuments: ['Veranstaltungskonzept', 'Sicherheitskonzept', 'Versicherung'],
    sourceKeywords: ['veranstaltung', 'sondernutzung'],
    relevantServiceKeywords: ['veranstaltung'],
    catalogServiceIds: [],
    uncataloguedStepLabels: ['Veranstaltungsgenehmigung'],
    missingQuestions: [q('size', 'Wie viele Besucher werden erwartet?', 'Wie viele Besucher werden erwartet?', /\d+|klein|groß/i)],
    summaryDu: 'Du planst eine Veranstaltung mit behördlichen Anforderungen in Kirkel.',
    summarySie: 'Sie planen eine Veranstaltung mit behördlichen Anforderungen in Kirkel.',
  }),
  tpl({
    id: 'ecommerce_start',
    title: 'Onlinehandel starten',
    domain: 'business',
    priority: 'mvp',
    triggerPhrases: ['onlinehandel', 'e-commerce', 'onlineshop', 'webshop gewerbe'],
    defaultMode: 'business',
    topicLabels: ['Handel', 'Digital'],
    orderedSteps: ['Gewerbe anmelden', 'Steuer und Impressum', 'Verbraucherschutz prüfen', KIRKEL],
    suggestedAuthorities: ['Gewerbeamt Kirkel', 'Finanzamt', 'IHK'],
    requiredDocuments: ['Gewerbeanmeldung', 'AGB/Impressum', 'Datenschutzkonzept'],
    sourceKeywords: ['onlinehandel', 'ecommerce', 'gewerbe'],
    relevantServiceKeywords: ['online', 'gewerbe'],
    catalogServiceIds: ['vc-gewerbe', 'vc-finanzamt'],
    uncataloguedStepLabels: [],
    missingQuestions: [q('ship', 'Versand ins Ausland geplant?', 'Versand ins Ausland geplant?', /ausland|eu|international/i)],
    summaryDu: 'Du startest einen Onlinehandel und brauchst behördliche Orientierung.',
    summarySie: 'Sie starten einen Onlinehandel und brauchen behördliche Orientierung.',
  }),
  tpl({
    id: 'public_procurement_readiness',
    title: 'Öffentliche Aufträge',
    domain: 'business',
    priority: 'mvp',
    triggerPhrases: ['öffentlicher auftrag', 'vergabe', 'ausschreibung', 'lieferant kommune'],
    defaultMode: 'business',
    topicLabels: ['Vergabe'],
    orderedSteps: ['Eignung prüfen', 'Vergabeportale nutzen', 'Unterlagen vorbereiten', KIRKEL],
    suggestedAuthorities: ['Vergabestelle', 'IHK', 'Kommune Kirkel'],
    requiredDocuments: ['Handelsregisterauszug', 'Referenzen', 'Eigenerklärungen'],
    sourceKeywords: ['vergabe', 'ausschreibung', 'öffentlicher auftrag'],
    relevantServiceKeywords: ['vergabe'],
    catalogServiceIds: [],
    uncataloguedStepLabels: ['Vergabeplattform'],
    missingQuestions: [q('sector', 'Welche Branche / Leistung?', 'Welche Branche / Leistung?', /branche|leistung|bau|it/i)],
    summaryDu: 'Du möchtest dich auf öffentliche Aufträge vorbereiten.',
    summarySie: 'Sie möchten sich auf öffentliche Aufträge vorbereiten.',
  }),
];

export function getMastercaseTemplateById(id: CivicJourneyId): CivicJourneyTemplate | undefined {
  return MASTERCASE_JOURNEY_MATRIX.find((t) => t.id === id);
}
