import { action, mastercase } from '@/lib/civic/mastercaseMatrixCore';

const KIRKEL_CTX = ['municipality', 'federalState'];

export const BUSINESS_MASTERCASES = [
  // ── Gewerbe starten ─────────────────────────────────────────────
  mastercase({
    id: 'business_registration',
    title: 'Gewerbe anmelden',
    domain: 'business',
    category: 'Gewerbe starten',
    priority: 'mvp',
    journeyId: 'business_registration',
    triggerPhrases: ['gewerbe anmelden', 'gewerbeanmeldung', 'selbstständig machen'],
    userIntentExamples: ['Ich möchte ein Gewerbe in Kirkel anmelden.'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Gewerbeamt Kirkel', 'Finanzamt', 'IHK', 'Berufsgenossenschaft'],
    orderedActions: [
      action('Tätigkeit und Rechtsform klären', 'Beratung / IHK', { status: 'required', sourceRequirement: 'template' }),
      action('Gewerbe anmelden', 'Gewerbeamt Kirkel', { status: 'required', sourceRequirement: 'regional', officialActionId: 'trade_register', notes: 'Zuständige Stelle suchen — kein erfundener Kommunal-Link' }),
      action('Steuerliche Erfassung', 'Finanzamt', { status: 'required', sourceRequirement: 'verified', officialActionId: 'tax_registration' }),
      action('Kammer / IHK prüfen', 'IHK', { status: 'conditional', sourceRequirement: 'verified', officialActionId: 'chamber_check' }),
      action('Berufsgenossenschaft', 'Berufsgenossenschaft', { status: 'required', sourceRequirement: 'verified', officialActionId: 'bg_register' }),
    ],
    requiredDocuments: ['Ausweis', 'Gewerbeanmeldung'],
    optionalDocuments: ['Handwerkskarte'],
    officialActionIds: ['trade_register', 'tax_registration', 'chamber_check', 'bg_register'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: ['Welche Tätigkeit?', 'Einzelunternehmen oder Gesellschaft?'],
    safetyNotes: [],
    testInputs: ['Ich möchte ein Gewerbe in Kirkel anmelden.'],
  }),
  mastercase({
    id: 'freelance_tax_registration',
    title: 'Freiberufler / Steuer',
    domain: 'business',
    category: 'Gewerbe starten',
    priority: 'mvp',
    journeyId: 'self_employed_start',
    triggerPhrases: ['freiberufler', 'freelance', 'freiberuflich'],
    userIntentExamples: ['Ich starte als Freiberufler — was muss ich beim Finanzamt tun?'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Finanzamt', 'Krankenkasse'],
    orderedActions: [
      action('Freiberuf vs. Gewerbe klären', 'Finanzamt / IHK', { status: 'required', sourceRequirement: 'verified', officialActionId: 'freelance_vs_trade' }),
      action('Steuerliche Erfassung', 'Finanzamt', { status: 'required', sourceRequirement: 'verified', officialActionId: 'tax_registration' }),
      action('Sozialversicherung klären', 'Krankenkasse', { status: 'required', sourceRequirement: 'missing', officialActionId: 'self_employed_social' }),
    ],
    requiredDocuments: ['Ausweis', 'Steuer-ID'],
    optionalDocuments: ['Businessplan'],
    officialActionIds: ['freelance_vs_trade', 'tax_registration', 'self_employed_social'],
    regionalLookupRequired: false,
    sourceStatus: 'verified_catalog',
    missingQuestions: ['Freiberuf oder Gewerbe?'],
    safetyNotes: [],
    testInputs: ['Ich werde freiberuflich tätig.'],
  }),
  mastercase({
    id: 'craft_business_start',
    title: 'Handwerksbetrieb starten',
    domain: 'business',
    category: 'Gewerbe starten',
    priority: 'mvp',
    journeyId: 'craft_business_start',
    triggerPhrases: ['handwerk', 'handwerkskammer', 'meister', 'handwerksbetrieb'],
    userIntentExamples: ['Ich starte einen Handwerksbetrieb.'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Handwerkskammer', 'Gewerbeamt Kirkel', 'Finanzamt'],
    orderedActions: [
      action('Meisterpflicht / Qualifikation prüfen', 'Handwerkskammer', { status: 'required', sourceRequirement: 'verified', officialActionId: 'craft_qualification' }),
      action('Gewerbe anmelden', 'Gewerbeamt Kirkel', { status: 'required', sourceRequirement: 'regional', officialActionId: 'trade_register' }),
      action('Handwerksrolle prüfen', 'Handwerkskammer', { status: 'conditional', sourceRequirement: 'verified', officialActionId: 'craft_roll_check' }),
    ],
    requiredDocuments: ['Meisterbrief', 'Ausweis', 'Gewerbeanmeldung'],
    optionalDocuments: [],
    officialActionIds: ['craft_qualification', 'trade_register', 'craft_roll_check'],
    regionalLookupRequired: true,
    sourceStatus: 'verified_catalog',
    missingQuestions: ['Welches Handwerk?'],
    safetyNotes: [],
    testInputs: ['Ich eröffne einen Handwerksbetrieb als Elektriker.'],
  }),
  mastercase({
    id: 'cafe_or_food_business_start',
    title: 'Gastronomie / Café eröffnen',
    domain: 'business',
    category: 'Gewerbe starten',
    priority: 'mvp',
    journeyId: 'gastronomy_permit',
    triggerPhrases: ['café', 'restaurant eröffnen', 'gastronomie', 'gaststätte'],
    userIntentExamples: ['Ich möchte ein Café eröffnen.'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Gewerbeamt Kirkel', 'Ordnungsamt', 'Gesundheitsamt'],
    orderedActions: [
      action('Gewerbe anmelden', 'Gewerbeamt Kirkel', { status: 'required', sourceRequirement: 'regional', officialActionId: 'trade_register' }),
      action('Gaststättenerlaubnis prüfen', 'Ordnungsamt / Gewerbeamt', { status: 'required', sourceRequirement: 'regional', officialActionId: 'gastronomy_permit_apply' }),
      action('Lebensmittelhygiene / Gesundheitsamt', 'Gesundheitsamt', { status: 'required', sourceRequirement: 'regional', officialActionId: 'health_food_authority' }),
    ],
    requiredDocuments: ['Gewerbeanmeldung', 'Hygieneunterlagen', 'Konzept'],
    optionalDocuments: [],
    officialActionIds: ['trade_register', 'gastronomy_permit_apply', 'health_food_authority'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: ['Wird Alkohol ausgeschenkt?'],
    safetyNotes: [],
    testInputs: ['Ich plane ein Café mit kleiner Küche in Kirkel.'],
  }),
  mastercase({
    id: 'company_relocation',
    title: 'Betriebsverlegung',
    domain: 'business',
    category: 'Gewerbe starten',
    priority: 'important',
    journeyId: 'business_change_deregister',
    triggerPhrases: ['betrieb verlegen', 'firma umziehen', 'gewerbe ummelden standort'],
    userIntentExamples: ['Ich verlege meinen Betrieb nach Kirkel.'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Gewerbeamt Kirkel', 'Finanzamt', 'IHK'],
    orderedActions: [
      action('Gewerbe ummelden', 'Gewerbeamt Kirkel', { status: 'required', sourceRequirement: 'regional', officialActionId: 'trade_relocate' }),
      action('Finanzamt informieren', 'Finanzamt', { status: 'required', sourceRequirement: 'verified', officialActionId: 'finanzamt_inform_close' }),
    ],
    requiredDocuments: ['Gewerbeschein', 'Mietvertrag neuer Standort'],
    optionalDocuments: [],
    officialActionIds: ['trade_relocate', 'finanzamt_inform_close'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: ['Neuer Standort in Kirkel?'],
    safetyNotes: [],
    testInputs: ['Ich ziehe mit meinem Gewerbe nach Kirkel um.'],
  }),
  mastercase({
    id: 'business_deregistration',
    title: 'Gewerbe abmelden',
    domain: 'business',
    category: 'Gewerbe starten',
    priority: 'important',
    journeyId: 'business_change_deregister',
    triggerPhrases: ['gewerbe abmelden', 'betrieb schließen', 'geschäftsaufgabe'],
    userIntentExamples: ['Ich möchte mein Gewerbe abmelden.'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Gewerbeamt Kirkel', 'Finanzamt', 'IHK'],
    orderedActions: [
      action('Gewerbe abmelden', 'Gewerbeamt Kirkel', { status: 'required', sourceRequirement: 'regional', officialActionId: 'trade_deregister' }),
      action('Finanzamt informieren', 'Finanzamt', { status: 'required', sourceRequirement: 'verified', officialActionId: 'finanzamt_inform_close' }),
    ],
    requiredDocuments: ['Gewerbeschein'],
    optionalDocuments: ['Schlussbilanz'],
    officialActionIds: ['trade_deregister', 'finanzamt_inform_close'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: ['Komplette Aufgabe oder nur Tätigkeitsänderung?'],
    safetyNotes: [],
    testInputs: ['Ich gebe mein Gewerbe auf.'],
  }),
  mastercase({
    id: 'business_change_registration',
    title: 'Gewerbeänderung',
    domain: 'business',
    category: 'Gewerbe starten',
    priority: 'important',
    journeyId: 'business_change_deregister',
    triggerPhrases: ['gewerbe ändern', 'tätigkeit ändern', 'gewerbe ummelden'],
    userIntentExamples: ['Ich ändere die Tätigkeit meines Gewerbes.'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Gewerbeamt Kirkel', 'Finanzamt'],
    orderedActions: [
      action('Änderung beim Gewerbeamt melden', 'Gewerbeamt Kirkel', { status: 'required', sourceRequirement: 'regional', officialActionId: 'trade_relocate' }),
      action('Kammer aktualisieren', 'IHK / HWK', { status: 'optional', sourceRequirement: 'verified', officialActionId: 'chamber_update' }),
    ],
    requiredDocuments: ['Gewerbeschein'],
    optionalDocuments: [],
    officialActionIds: ['trade_relocate', 'chamber_update'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: ['Welche Änderung genau?'],
    safetyNotes: [],
    testInputs: ['Ich erweitere die Tätigkeit meines Gewerbes.'],
  }),

  // ── Arbeitgeberpflichten ────────────────────────────────────────
  mastercase({
    id: 'first_employee_hiring',
    title: 'Erste Mitarbeitende einstellen',
    domain: 'employer',
    category: 'Arbeitgeberpflichten',
    priority: 'mvp',
    journeyId: 'employer_onboarding',
    triggerPhrases: ['erste mitarbeiter', 'mitarbeiter einstellen', 'personal einstellen', 'arbeitgeber werden'],
    userIntentExamples: ['Ich stelle zum ersten Mal Mitarbeitende ein.'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Finanzamt', 'Krankenkasse', 'Berufsgenossenschaft', 'Agentur für Arbeit (Betriebsnummer)'],
    orderedActions: [
      action('Betriebsnummer beantragen', 'Bundesagentur für Arbeit', { status: 'required', sourceRequirement: 'verified', officialActionId: 'employer_number' }),
      action('Sozialversicherungsmeldungen vorbereiten', 'Krankenkasse', { status: 'required', sourceRequirement: 'verified', officialActionId: 'social_insurance_employer' }),
      action('Lohnsteuer / ELSTER klären', 'Finanzamt', { status: 'required', sourceRequirement: 'verified', officialActionId: 'payroll_tax_elster' }),
      action('Berufsgenossenschaft prüfen', 'Berufsgenossenschaft', { status: 'required', sourceRequirement: 'verified', officialActionId: 'bg_register' }),
      action('Arbeitsvertrag vorbereiten', 'Arbeitgeber', { status: 'advisory', sourceRequirement: 'template', officialActionId: 'employment_contract_orientation' }),
    ],
    requiredDocuments: ['Arbeitsverträge', 'SV-Meldungen'],
    optionalDocuments: ['Lohnunterlagen'],
    officialActionIds: ['employer_number', 'social_insurance_employer', 'payroll_tax_elster', 'bg_register', 'employment_contract_orientation'],
    regionalLookupRequired: false,
    sourceStatus: 'verified_catalog',
    missingQuestions: ['Vollzeit, Teilzeit oder Minijob?'],
    safetyNotes: [],
    testInputs: ['Ich stelle zum ersten Mal Mitarbeitende ein.'],
  }),
  mastercase({
    id: 'employer_company_number',
    title: 'Betriebsnummer',
    domain: 'employer',
    category: 'Arbeitgeberpflichten',
    priority: 'mvp',
    journeyId: 'employer_onboarding',
    triggerPhrases: ['betriebsnummer', 'arbeitgeber nummer'],
    userIntentExamples: ['Ich brauche eine Betriebsnummer als Arbeitgeber.'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Bundesagentur für Arbeit'],
    orderedActions: [
      action('Betriebsnummer beantragen', 'Bundesagentur für Arbeit', { status: 'required', sourceRequirement: 'verified', officialActionId: 'employer_number' }),
    ],
    requiredDocuments: ['Gewerbeanmeldung', 'Ausweis'],
    optionalDocuments: [],
    officialActionIds: ['employer_number'],
    regionalLookupRequired: false,
    sourceStatus: 'verified_catalog',
    missingQuestions: [],
    safetyNotes: [],
    testInputs: ['Wie bekomme ich eine Betriebsnummer?'],
  }),
  mastercase({
    id: 'social_security_registration',
    title: 'Sozialversicherung melden',
    domain: 'employer',
    category: 'Arbeitgeberpflichten',
    priority: 'mvp',
    journeyId: 'employer_onboarding',
    triggerPhrases: ['sozialversicherung melden', 'sv meldung', 'meldeverfahren'],
    userIntentExamples: ['Wie melde ich Mitarbeitende zur Sozialversicherung?'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Krankenkasse', 'Bundesagentur für Arbeit'],
    orderedActions: [
      action('Sozialversicherungsmeldungen', 'Krankenkasse', { status: 'required', sourceRequirement: 'verified', officialActionId: 'social_insurance_employer' }),
    ],
    requiredDocuments: ['Arbeitsverträge', 'SV-Meldungen'],
    optionalDocuments: [],
    officialActionIds: ['social_insurance_employer'],
    regionalLookupRequired: false,
    sourceStatus: 'verified_catalog',
    missingQuestions: [],
    safetyNotes: [],
    testInputs: ['Sozialversicherung für neue Mitarbeitende melden.'],
  }),
  mastercase({
    id: 'payroll_tax_registration',
    title: 'Lohnsteuer & ELSTER',
    domain: 'employer',
    category: 'Arbeitgeberpflichten',
    priority: 'important',
    journeyId: 'employer_onboarding',
    triggerPhrases: ['lohnsteuer', 'elster arbeitgeber', 'lohnabrechnung'],
    userIntentExamples: ['Was muss ich bei Lohnsteuer und ELSTER beachten?'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Finanzamt'],
    orderedActions: [
      action('Lohnsteuer-Anmeldung / ELSTER', 'Finanzamt', { status: 'required', sourceRequirement: 'verified', officialActionId: 'payroll_tax_elster' }),
    ],
    requiredDocuments: ['Steuernummer', 'Lohnunterlagen'],
    optionalDocuments: [],
    officialActionIds: ['payroll_tax_elster'],
    regionalLookupRequired: false,
    sourceStatus: 'verified_catalog',
    missingQuestions: [],
    safetyNotes: [],
    testInputs: ['Lohnsteuer als Arbeitgeber — ELSTER?'],
  }),
  mastercase({
    id: 'accident_insurance_bg',
    title: 'Berufsgenossenschaft',
    domain: 'employer',
    category: 'Arbeitgeberpflichten',
    priority: 'important',
    journeyId: 'employer_onboarding',
    triggerPhrases: ['berufsgenossenschaft', 'unfallversicherung arbeitgeber', 'bg meldung'],
    userIntentExamples: ['Welche Berufsgenossenschaft ist für meinen Betrieb zuständig?'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Berufsgenossenschaft'],
    orderedActions: [
      action('BG-Meldung / Unfallversicherung', 'Berufsgenossenschaft', { status: 'required', sourceRequirement: 'verified', officialActionId: 'bg_register' }),
    ],
    requiredDocuments: ['Gewerbeanmeldung', 'Tätigkeitsbeschreibung'],
    optionalDocuments: [],
    officialActionIds: ['bg_register'],
    regionalLookupRequired: false,
    sourceStatus: 'verified_catalog',
    missingQuestions: ['Welche Branche / Tätigkeit?'],
    safetyNotes: [],
    testInputs: ['Berufsgenossenschaft für meinen Betrieb finden.'],
  }),
  mastercase({
    id: 'mini_job_registration',
    title: 'Minijob anmelden',
    domain: 'employer',
    category: 'Arbeitgeberpflichten',
    priority: 'important',
    journeyId: 'employer_onboarding',
    triggerPhrases: ['minijob', 'geringfügig beschäftigt', '450 euro job'],
    userIntentExamples: ['Ich möchte jemanden geringfügig beschäftigen.'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Minijob-Zentrale', 'Krankenkasse'],
    orderedActions: [
      action('Minijob anmelden', 'Minijob-Zentrale', { status: 'required', sourceRequirement: 'verified', officialActionId: 'social_insurance_employer', notes: 'Über Meldeverfahren / Minijob-Zentrale' }),
      action('Betriebsnummer falls nötig', 'Bundesagentur für Arbeit', { status: 'conditional', sourceRequirement: 'verified', officialActionId: 'employer_number' }),
    ],
    requiredDocuments: ['Arbeitsvertrag'],
    optionalDocuments: [],
    officialActionIds: ['social_insurance_employer', 'employer_number'],
    regionalLookupRequired: false,
    sourceStatus: 'verified_catalog',
    missingQuestions: ['Erster Minijob im Betrieb?'],
    safetyNotes: [],
    testInputs: ['Ich stelle einen Minijobber ein.'],
  }),

  // ── Betriebscompliance ──────────────────────────────────────────
  mastercase({
    id: 'trade_permit_required',
    title: 'Erlaubnispflichtige Tätigkeit',
    domain: 'business',
    category: 'Betriebscompliance',
    priority: 'important',
    journeyId: 'business_registration',
    triggerPhrases: ['erlaubnispflicht', 'genehmigung gewerbe', 'konzession'],
    userIntentExamples: ['Brauche ich eine Erlaubnis für meine Tätigkeit?'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Gewerbeamt Kirkel', 'Ordnungsamt'],
    orderedActions: [
      action('Erlaubnispflicht prüfen', 'Gewerbeamt / IHK', { status: 'required', sourceRequirement: 'verified', officialActionId: 'permit_activity_check' }),
      action('Gewerbe anmelden', 'Gewerbeamt Kirkel', { status: 'required', sourceRequirement: 'regional', officialActionId: 'trade_register' }),
    ],
    requiredDocuments: ['Tätigkeitsbeschreibung'],
    optionalDocuments: [],
    officialActionIds: ['permit_activity_check', 'trade_register'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: ['Welche Tätigkeit genau?'],
    safetyNotes: [],
    testInputs: ['Ist meine geplante Tätigkeit erlaubnispflichtig?'],
  }),
  mastercase({
    id: 'restaurant_permit',
    title: 'Gaststättenerlaubnis',
    domain: 'business',
    category: 'Betriebscompliance',
    priority: 'mvp',
    journeyId: 'gastronomy_permit',
    triggerPhrases: ['gaststättenerlaubnis', 'schankerlaubnis', 'gastgewerbe'],
    userIntentExamples: ['Ich brauche eine Gaststättenerlaubnis.'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Ordnungsamt Kirkel', 'Gewerbeamt'],
    orderedActions: [
      action('Gaststättenerlaubnis beantragen', 'Ordnungsamt / Gewerbeamt', { status: 'required', sourceRequirement: 'regional', officialActionId: 'gastronomy_permit_apply' }),
    ],
    requiredDocuments: ['Konzept', 'Gewerbeanmeldung'],
    optionalDocuments: ['Führungszeugnis'],
    officialActionIds: ['gastronomy_permit_apply'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: ['Alkoholausschank geplant?'],
    safetyNotes: [],
    testInputs: ['Gaststättenerlaubnis für Restaurant in Kirkel.'],
  }),
  mastercase({
    id: 'hygiene_food_business',
    title: 'Lebensmittelhygiene',
    domain: 'business',
    category: 'Betriebscompliance',
    priority: 'important',
    journeyId: 'gastronomy_permit',
    triggerPhrases: ['lebensmittelhygiene', 'haccp', 'gesundheitsamt gastronomie'],
    userIntentExamples: ['Welche Hygienevorgaben gelten für mein Lebensmittelgeschäft?'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Gesundheitsamt'],
    orderedActions: [
      action('Hygiene / Lebensmittelüberwachung', 'Gesundheitsamt', { status: 'required', sourceRequirement: 'regional', officialActionId: 'health_food_authority' }),
    ],
    requiredDocuments: ['Hygienekonzept'],
    optionalDocuments: [],
    officialActionIds: ['health_food_authority'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: [],
    safetyNotes: [],
    testInputs: ['Hygieneauflagen für Bäckerei — was prüft das Gesundheitsamt?'],
  }),
  mastercase({
    id: 'data_protection_basic',
    title: 'Datenschutz & Impressum',
    domain: 'business',
    category: 'Betriebscompliance',
    priority: 'important',
    journeyId: 'ecommerce_start',
    triggerPhrases: ['datenschutz', 'dsgvo', 'impressum', 'online shop'],
    userIntentExamples: ['Ich starte einen Online-Shop — was brauche ich rechtlich?'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Datenschutzbehörde (Orientierung)', 'Gewerbeamt'],
    orderedActions: [
      action('Impressum und Datenschutz vorbereiten', 'Unternehmen', { status: 'required', sourceRequirement: 'template', officialActionId: 'privacy_imprint_orientation' }),
      action('Gewerbe anmelden', 'Gewerbeamt Kirkel', { status: 'required', sourceRequirement: 'regional', officialActionId: 'trade_register' }),
    ],
    requiredDocuments: ['Datenschutzkonzept', 'AGB/Impressum'],
    optionalDocuments: [],
    officialActionIds: ['privacy_imprint_orientation', 'trade_register'],
    regionalLookupRequired: true,
    sourceStatus: 'template_only',
    missingQuestions: ['B2C oder B2B?'],
    safetyNotes: ['Keine Rechtsberatung — Orientierung nur.'],
    testInputs: ['Online-Shop starten — Datenschutz und Impressum.'],
  }),
  mastercase({
    id: 'local_municipal_permit',
    title: 'Kommunale Genehmigung',
    domain: 'mixed',
    category: 'Betriebscompliance',
    priority: 'later',
    journeyId: 'event_special_use',
    triggerPhrases: ['sondernutzung', 'straße sperren', 'veranstaltung genehmigung'],
    userIntentExamples: ['Ich brauche eine Genehmigung von der Kommune.'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Ordnungsamt Kirkel', 'Gewerbeamt'],
    orderedActions: [
      action('Sondernutzung / Veranstaltung anmelden', 'Ordnungsamt Kirkel', { status: 'required', sourceRequirement: 'regional', officialActionId: 'special_use_apply' }),
    ],
    requiredDocuments: ['Konzept', 'Sicherheitskonzept'],
    optionalDocuments: ['Versicherung'],
    officialActionIds: ['special_use_apply', 'event_register'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: ['Öffentlicher Raum betroffen?'],
    safetyNotes: [],
    testInputs: ['Straßenfest in Kirkel — Genehmigung?'],
  }),

  // ── Förderung & Beratung ────────────────────────────────────────
  mastercase({
    id: 'business_grants_saarland',
    title: 'Förderung Saarland',
    domain: 'business',
    category: 'Förderung & Beratung',
    priority: 'important',
    journeyId: 'funding_startup',
    triggerPhrases: ['förderung saarland', 'wirtschaftsförderung saarland'],
    userIntentExamples: ['Gibt es Fördermittel für Gründer im Saarland?'],
    knownContextUsage: ['federalState', 'municipality'],
    responsibleAuthorities: ['Wirtschaftsförderung Saarland', 'IHK'],
    orderedActions: [
      action('Regionale Förderprogramme prüfen', 'Wirtschaftsförderung', { status: 'required', sourceRequirement: 'regional', officialActionId: 'regional_funding' }),
      action('Förderdatenbank durchsuchen', 'Bund / Land', { status: 'advisory', sourceRequirement: 'verified', officialActionId: 'funding_database' }),
    ],
    requiredDocuments: ['Businessplan', 'Finanzplan'],
    optionalDocuments: [],
    officialActionIds: ['regional_funding', 'funding_database'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: ['Gründung oder Expansion?'],
    safetyNotes: [],
    testInputs: ['Fördermittel für Startup im Saarland.'],
  }),
  mastercase({
    id: 'startup_funding',
    title: 'Gründungsförderung',
    domain: 'business',
    category: 'Förderung & Beratung',
    priority: 'mvp',
    journeyId: 'funding_startup',
    triggerPhrases: ['gründungszuschuss', 'existenzgründung', 'fördermittel gründung'],
    userIntentExamples: ['Ich suche Fördermittel für meine Existenzgründung.'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['IHK', 'Agentur für Arbeit', 'Förderstelle'],
    orderedActions: [
      action('Gründungszuschuss / Beratung prüfen', 'Agentur für Arbeit / IHK', { status: 'conditional', sourceRequirement: 'verified', officialActionId: 'founding_grant_counselling' }),
      action('Förderdatenbank', 'Bund / Land', { status: 'advisory', sourceRequirement: 'verified', officialActionId: 'funding_database' }),
      action('Businessplan vorbereiten', 'Unternehmen', { status: 'required', sourceRequirement: 'template', officialActionId: 'business_plan_prep' }),
    ],
    requiredDocuments: ['Businessplan', 'Finanzplan'],
    optionalDocuments: [],
    officialActionIds: ['founding_grant_counselling', 'funding_database', 'business_plan_prep'],
    regionalLookupRequired: true,
    sourceStatus: 'verified_catalog',
    missingQuestions: ['Aus Arbeitslosigkeit gründend?'],
    safetyNotes: [],
    testInputs: ['Existenzgründung — welche Förderung gibt es?'],
  }),
  mastercase({
    id: 'training_grants_employer',
    title: 'Weiterbildungsförderung Arbeitgeber',
    domain: 'employer',
    category: 'Förderung & Beratung',
    priority: 'later',
    journeyId: 'employer_onboarding',
    triggerPhrases: ['weiterbildung mitarbeiter förderung', 'qualifizierung betrieb'],
    userIntentExamples: ['Kann ich Weiterbildung für Mitarbeitende fördern lassen?'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Agentur für Arbeit', 'IHK'],
    orderedActions: [
      action('Qualifizierungsförderung prüfen', 'Agentur für Arbeit / IHK', { status: 'advisory', sourceRequirement: 'verified', officialActionId: 'training_counselling' }),
    ],
    requiredDocuments: ['Qualifizierungsplan'],
    optionalDocuments: [],
    officialActionIds: ['training_counselling'],
    regionalLookupRequired: false,
    sourceStatus: 'verified_catalog',
    missingQuestions: [],
    safetyNotes: [],
    testInputs: ['Weiterbildung für Mitarbeitende fördern.'],
  }),
  mastercase({
    id: 'digitalization_funding',
    title: 'Digitalisierungsförderung',
    domain: 'business',
    category: 'Förderung & Beratung',
    priority: 'later',
    journeyId: 'funding_startup',
    triggerPhrases: ['digitalisierung förderung', 'digital bonus', 'it förderung'],
    userIntentExamples: ['Gibt es Förderung für Digitalisierung meines Betriebs?'],
    knownContextUsage: ['federalState'],
    responsibleAuthorities: ['Wirtschaftsförderung', 'IHK'],
    orderedActions: [
      action('Förderprogramme prüfen', 'Wirtschaftsförderung Saarland', { status: 'advisory', sourceRequirement: 'regional', officialActionId: 'regional_funding' }),
    ],
    requiredDocuments: ['Digitalisierungsplan'],
    optionalDocuments: [],
    officialActionIds: ['regional_funding', 'funding_database'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: [],
    safetyNotes: [],
    testInputs: ['Digitalisierung im Handwerk fördern lassen.'],
  }),
];
