import { action, mastercase, GOVERNANCE_DEFAULT } from '@/lib/civic/mastercaseMatrixCore';

const KIRKEL_CTX = ['municipality', 'federalState', 'demo_profile'];

export const PRIVATE_MASTERCASES = [
  // ── Familie & Kind ────────────────────────────────────────────────
  mastercase({
    id: 'child_birth_family_benefits',
    title: 'Geburt & Familienleistungen',
    domain: 'private',
    category: 'Familie & Kind',
    priority: 'mvp',
    journeyId: 'child_birth_kita',
    triggerPhrases: ['bekomme ein kind', 'geburt', 'schwanger', 'elterngeld', 'kindergeld', 'baby'],
    userIntentExamples: ['Ich bekomme ein Kind. An was muss ich alles denken?'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Standesamt Kirkel', 'Familienkasse', 'Krankenkasse', 'Arbeitgeber'],
    orderedActions: [
      action('Geburt beim Standesamt beurkunden / Geburtsurkunde', 'Standesamt Kirkel', {
        status: 'required',
        sourceRequirement: 'regional',
        officialActionId: 'birth_register',
        documents: ['Ausweis', 'Muttpass'],
        notes: 'Regional — Zuständige Stelle suchen',
      }),
      action('Elterngeld vorbereiten', 'Familienkasse', {
        status: 'required',
        sourceRequirement: 'verified',
        officialActionId: 'elterngeld_apply',
        timing: 'nach Geburt',
      }),
      action('Kindergeld vorbereiten', 'Familienkasse', {
        status: 'required',
        sourceRequirement: 'verified',
        officialActionId: 'kindergeld_apply',
      }),
      action('Krankenversicherung Kind klären', 'Krankenkasse', {
        status: 'required',
        sourceRequirement: 'missing',
        officialActionId: 'family_insurance',
      }),
      action('Kita-Platz optional vormerken', 'Kommune / Jugendamt', {
        status: 'optional',
        sourceRequirement: 'regional',
        officialActionId: 'kita_reserve',
      }),
      action('Elternzeit / Arbeitgeber optional', 'Arbeitgeber', {
        status: 'optional',
        sourceRequirement: 'template',
        officialActionId: 'parental_leave_employer',
      }),
    ],
    requiredDocuments: ['Ausweis', 'Geburtsurkunde', 'Steuer-ID', 'Einkommensnachweise'],
    optionalDocuments: ['Krankenkassendaten', 'Arbeitgeberbescheinigung'],
    officialActionIds: ['birth_register', 'elterngeld_apply', 'kindergeld_apply', 'family_insurance', 'kita_reserve', 'parental_leave_employer'],
    regionalLookupRequired: true,
    sourceStatus: 'verified_catalog',
    missingQuestions: ['Ist das Kind bereits geboren?', 'Ab wann wird Betreuung benötigt?'],
    safetyNotes: [],
    testInputs: ['Ich bekomme ein Kind. An was muss ich alles denken?'],
  }),
  mastercase({
    id: 'child_kita_place',
    title: 'Kita-Platz',
    domain: 'private',
    category: 'Familie & Kind',
    priority: 'mvp',
    journeyId: 'childcare_school',
    triggerPhrases: ['kita platz', 'kita anmeldung', 'kinderbetreuung', 'hort platz'],
    userIntentExamples: ['Ich brauche einen Kita-Platz in Kirkel.'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Kommune Kirkel', 'Jugendamt'],
    orderedActions: [
      action('Betreuungsbedarf klären', 'Kommune / Jugendamt', { status: 'required', sourceRequirement: 'regional', officialActionId: 'kita_reserve' }),
      action('Anmeldung vorbereiten', 'Kommune Kirkel', { status: 'required', sourceRequirement: 'regional', notes: 'Zuständige Stelle suchen' }),
    ],
    requiredDocuments: ['Wohnsitznachweis', 'Geburtsurkunde oder Schwangerschaftsnachweis'],
    optionalDocuments: ['Arbeitgeberbescheinigung'],
    officialActionIds: ['kita_reserve'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: ['Welches Alter hat das Kind?'],
    safetyNotes: [],
    testInputs: ['Ich suche einen Kita-Platz für mein Kind in Kirkel.'],
  }),
  mastercase({
    id: 'child_school_enrollment',
    title: 'Schulanmeldung',
    domain: 'private',
    category: 'Familie & Kind',
    priority: 'important',
    journeyId: 'childcare_school',
    triggerPhrases: ['schulanmeldung', 'schule anmelden', 'einschulung', 'schulplatz'],
    userIntentExamples: ['Mein Kind soll eingeschult werden — was brauche ich?'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Schule', 'Schulamt', 'Kommune Kirkel'],
    orderedActions: [
      action('Schulbezirk und Schule klären', 'Kommune / Schulamt', { status: 'required', sourceRequirement: 'regional', officialActionId: 'school_transfer' }),
      action('Anmeldung vorbereiten', 'Schule', { status: 'required', sourceRequirement: 'regional' }),
    ],
    requiredDocuments: ['Impfpass', 'Meldebescheinigung', 'Ausweis'],
    optionalDocuments: ['Zeugnisse'],
    officialActionIds: ['school_transfer'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: ['Welches Schuljahr?', 'Schulwechsel oder Erstanmeldung?'],
    safetyNotes: [],
    testInputs: ['Ich muss mein Kind für die Schule anmelden.'],
  }),
  mastercase({
    id: 'parental_allowance',
    title: 'Elterngeld',
    domain: 'private',
    category: 'Familie & Kind',
    priority: 'mvp',
    journeyId: 'child_birth_kita',
    triggerPhrases: ['elterngeld', 'elternzeit', 'elterngeldantrag'],
    userIntentExamples: ['Wie beantrage ich Elterngeld?'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Familienkasse', 'Arbeitgeber'],
    orderedActions: [
      action('Elterngeld beantragen vorbereiten', 'Familienkasse', { status: 'required', sourceRequirement: 'verified', officialActionId: 'elterngeld_apply' }),
      action('Arbeitgeber / Elternzeit abstimmen', 'Arbeitgeber', { status: 'optional', sourceRequirement: 'template', officialActionId: 'parental_leave_employer' }),
    ],
    requiredDocuments: ['Geburtsurkunde', 'Einkommensnachweise'],
    optionalDocuments: ['Mutterschaftsgeld-Bescheid'],
    officialActionIds: ['elterngeld_apply', 'parental_leave_employer'],
    regionalLookupRequired: false,
    sourceStatus: 'verified_catalog',
    missingQuestions: ['Ist das Kind bereits geboren?'],
    safetyNotes: ['ElterngeldDigital je nach Bundesland unterschiedlich verfügbar.'],
    testInputs: ['Ich möchte Elterngeld beantragen.'],
  }),
  mastercase({
    id: 'child_benefit',
    title: 'Kindergeld',
    domain: 'private',
    category: 'Familie & Kind',
    priority: 'mvp',
    journeyId: 'child_birth_kita',
    triggerPhrases: ['kindergeld', 'kindergeldantrag'],
    userIntentExamples: ['Wie bekomme ich Kindergeld?'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Familienkasse'],
    orderedActions: [
      action('Kindergeld beantragen', 'Familienkasse', { status: 'required', sourceRequirement: 'verified', officialActionId: 'kindergeld_apply' }),
    ],
    requiredDocuments: ['Kindergeldantrag', 'Geburtsurkunde', 'Steuer-ID des Kindes'],
    optionalDocuments: [],
    officialActionIds: ['kindergeld_apply'],
    regionalLookupRequired: false,
    sourceStatus: 'verified_catalog',
    missingQuestions: ['Liegt eine Geburtsurkunde vor?'],
    safetyNotes: [],
    testInputs: ['Ich brauche Kindergeld für mein Kind.'],
  }),
  mastercase({
    id: 'child_support_single_parent',
    title: 'Unterhalt & Alleinerziehend',
    domain: 'private',
    category: 'Familie & Kind',
    priority: 'important',
    journeyId: 'separation_support',
    triggerPhrases: ['unterhalt', 'alleinerziehend', 'kindesunterhalt'],
    userIntentExamples: ['Ich bin alleinerziehend und brauche Orientierung zu Unterhalt.'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Jugendamt', 'Beratungsstelle', 'Familienkasse'],
    orderedActions: [
      action('Unterhaltssituation klären', 'Jugendamt / Beratungsstelle', { status: 'required', sourceRequirement: 'regional', officialActionId: 'maintenance_advance' }),
      action('Kindergeld prüfen', 'Familienkasse', { status: 'optional', sourceRequirement: 'verified', officialActionId: 'kindergeld_apply' }),
    ],
    requiredDocuments: ['Einkommensnachweise', 'Nachweise Kinder'],
    optionalDocuments: ['Unterhaltsvereinbarung'],
    officialActionIds: ['maintenance_advance', 'kindergeld_apply'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: ['Gibt es einen Unterhaltstitel?'],
    safetyNotes: [],
    testInputs: ['Ich bin alleinerziehend und brauche Hilfe beim Kindesunterhalt.'],
  }),
  mastercase({
    id: 'custody_or_separation_support',
    title: 'Trennung & Sorge',
    domain: 'private',
    category: 'Familie & Kind',
    priority: 'mvp',
    journeyId: 'separation_support',
    triggerPhrases: ['trennung', 'scheidung', 'sorgerecht', 'getrennt'],
    userIntentExamples: ['Wir trennen uns — welche Behördenwege sind wichtig?'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Jugendamt', 'Beratungsstelle', 'Familiengericht (Orientierung)'],
    orderedActions: [
      action('Beratung und Anlaufstellen nutzen', 'Jugendamt / Beratungsstelle', { status: 'required', sourceRequirement: 'regional', officialActionId: 'youth_office_counselling' }),
      action('Unterlagen sammeln', 'Beratungsstelle', { status: 'advisory', sourceRequirement: 'template' }),
    ],
    requiredDocuments: ['Einkommensnachweise', 'Verträge'],
    optionalDocuments: ['Schreiben der anderen Partei'],
    officialActionIds: ['youth_office_counselling'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: ['Sind Kinder betroffen?'],
    safetyNotes: ['Keine Rechtsberatung zu Scheidung oder Sorgerecht.'],
    testInputs: ['Wir trennen uns und haben Kinder.'],
  }),

  // ── Wohnen & Umzug ──────────────────────────────────────────────
  mastercase({
    id: 'moving_with_children',
    title: 'Umzug mit Kindern',
    domain: 'private',
    category: 'Wohnen & Umzug',
    priority: 'mvp',
    journeyId: 'moving_with_children',
    triggerPhrases: ['umzug mit kindern', 'ziehe mit kindern', 'schulwechsel umzug'],
    userIntentExamples: ['Ich ziehe mit Kindern um und brauche Unterstützung.'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Bürgeramt Kirkel', 'Schule', 'Wohngeldstelle', 'Familienkasse'],
    orderedActions: [
      action('Wohnsitz anmelden', 'Bürgeramt Kirkel', { status: 'required', sourceRequirement: 'verified', officialActionId: 'residence_register' }),
      action('Schule / Kita prüfen', 'Schule / Kommune', { status: 'conditional', sourceRequirement: 'regional', officialActionId: 'school_kita_change' }),
      action('Wohngeld optional prüfen', 'Wohngeldstelle', { status: 'optional', sourceRequirement: 'verified', officialActionId: 'wohngeld_moving' }),
      action('Kfz optional ummelden', 'Zulassungsstelle', { status: 'conditional', sourceRequirement: 'regional', officialActionId: 'vehicle_reregister' }),
    ],
    requiredDocuments: ['Ausweis', 'Wohnungsgeberbestätigung', 'Mietvertrag'],
    optionalDocuments: ['Meldebescheinigung Kinder'],
    officialActionIds: ['residence_register', 'school_kita_change', 'wohngeld_moving', 'vehicle_reregister'],
    regionalLookupRequired: true,
    sourceStatus: 'verified_catalog',
    missingQuestions: ['Ziehst du nach Kirkel oder innerhalb Kirkel?'],
    safetyNotes: [],
    testInputs: ['Ich ziehe mit Kindern um und brauche Unterstützung.'],
  }),
  mastercase({
    id: 'change_of_address',
    title: 'Adressänderung / Ummeldung',
    domain: 'private',
    category: 'Wohnen & Umzug',
    priority: 'mvp',
    journeyId: 'moving_with_children',
    triggerPhrases: ['ummeldung', 'adresse ändern', 'wohnsitz anmelden', 'umzug'],
    userIntentExamples: ['Ich bin umgezogen und muss mich ummelden.'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Bürgeramt Kirkel'],
    orderedActions: [
      action('Wohnsitz anmelden', 'Bürgeramt Kirkel', { status: 'required', sourceRequirement: 'verified', officialActionId: 'residence_register' }),
      action('Ausweisadresse optional ändern', 'Bürgeramt Kirkel', { status: 'optional', sourceRequirement: 'regional', officialActionId: 'id_address_change' }),
    ],
    requiredDocuments: ['Ausweis', 'Wohnungsgeberbestätigung'],
    optionalDocuments: [],
    officialActionIds: ['residence_register', 'id_address_change'],
    regionalLookupRequired: true,
    sourceStatus: 'verified_catalog',
    missingQuestions: ['Innerhalb Deutschlands oder aus dem Ausland?'],
    safetyNotes: [],
    testInputs: ['Ich muss meinen Wohnsitz in Kirkel anmelden.'],
  }),
  mastercase({
    id: 'housing_benefit',
    title: 'Wohngeld',
    domain: 'private',
    category: 'Wohnen & Umzug',
    priority: 'mvp',
    journeyId: 'housing_support',
    triggerPhrases: ['wohngeld', 'wohnkosten', 'miete hoch'],
    userIntentExamples: ['Meine Miete ist hoch — gibt es Wohngeld?'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Wohngeldstelle'],
    orderedActions: [
      action('Wohngeld prüfen / beantragen', 'Wohngeldstelle', { status: 'required', sourceRequirement: 'verified', officialActionId: 'wohngeld_apply' }),
    ],
    requiredDocuments: ['Mietvertrag', 'Einkommensnachweise', 'Haushaltsmitglieder'],
    optionalDocuments: ['Kontoauszüge'],
    officialActionIds: ['wohngeld_apply'],
    regionalLookupRequired: true,
    sourceStatus: 'verified_catalog',
    missingQuestions: ['Wie viele Personen im Haushalt?'],
    safetyNotes: [],
    testInputs: ['Ich möchte Wohngeld beantragen.'],
  }),
  mastercase({
    id: 'low_income_support',
    title: 'Unterstützung bei geringem Einkommen',
    domain: 'private',
    category: 'Wohnen & Umzug',
    priority: 'important',
    journeyId: 'housing_support',
    triggerPhrases: ['einkommen reicht nicht', 'finanziell eng', 'sozialhilfe wohnen', 'niedriges einkommen'],
    userIntentExamples: ['Mein Einkommen reicht nicht für Miete und Leben.'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Wohngeldstelle', 'Jobcenter', 'Sozialamt Kirkel'],
    orderedActions: [
      action('Wohngeld prüfen', 'Wohngeldstelle', { status: 'required', sourceRequirement: 'verified', officialActionId: 'wohngeld_apply' }),
      action('Bürgergeld optional prüfen', 'Jobcenter', { status: 'conditional', sourceRequirement: 'missing', officialActionId: 'buergergeld_housing', notes: 'Kein Anspruch versprechen' }),
      action('Kinderzuschlag optional', 'Familienkasse', { status: 'conditional', sourceRequirement: 'verified', officialActionId: 'kinderzuschlag_check' }),
    ],
    requiredDocuments: ['Mietvertrag', 'Einkommensnachweise'],
    optionalDocuments: ['Kontoauszüge'],
    officialActionIds: ['wohngeld_apply', 'buergergeld_housing', 'kinderzuschlag_check'],
    regionalLookupRequired: true,
    sourceStatus: 'verified_catalog',
    missingQuestions: ['Gibt es Kinder im Haushalt?'],
    safetyNotes: [],
    testInputs: ['Mein Einkommen reicht nicht — welche Unterstützung gibt es?'],
  }),
  mastercase({
    id: 'residence_certificate',
    title: 'Meldebescheinigung',
    domain: 'private',
    category: 'Wohnen & Umzug',
    priority: 'important',
    journeyId: 'id_passport',
    triggerPhrases: ['meldebescheinigung', 'wohnungsgeberbestätigung', 'anmeldebestätigung'],
    userIntentExamples: ['Ich brauche eine Meldebescheinigung.'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Bürgeramt Kirkel'],
    orderedActions: [
      action('Meldebescheinigung beantragen', 'Bürgeramt Kirkel', { status: 'required', sourceRequirement: 'regional', notes: 'Zuständige Stelle suchen' }),
    ],
    requiredDocuments: ['Ausweis'],
    optionalDocuments: [],
    officialActionIds: [],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: ['Für welchen Zweck wird die Bescheinigung benötigt?'],
    safetyNotes: [],
    testInputs: ['Ich brauche eine Meldebescheinigung vom Bürgeramt.'],
  }),
  mastercase({
    id: 'parking_permit_or_vehicle_update',
    title: 'Fahrzeug & Parken',
    domain: 'private',
    category: 'Wohnen & Umzug',
    priority: 'important',
    journeyId: 'vehicle_registration',
    triggerPhrases: ['kfz', 'fahrzeug anmelden', 'zulassung', 'parkausweis', 'kennzeichen'],
    userIntentExamples: ['Ich muss mein Auto anmelden.'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Zulassungsstelle', 'Kommune Kirkel'],
    orderedActions: [
      action('Fahrzeug an- oder ummelden', 'Zulassungsstelle', { status: 'required', sourceRequirement: 'regional', officialActionId: 'vehicle_register' }),
      action('Parkausweis optional prüfen', 'Kommune Kirkel', { status: 'optional', sourceRequirement: 'regional', notes: 'Zuständige Stelle suchen' }),
    ],
    requiredDocuments: ['Fahrzeugbrief', 'Ausweis', 'Versicherungsnachweis'],
    optionalDocuments: ['TÜV-Bescheinigung'],
    officialActionIds: ['vehicle_register', 'vehicle_reregister'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: ['Neuanschaffung oder Ummeldung?'],
    safetyNotes: [],
    testInputs: ['Ich muss mein Fahrzeug zulassen.'],
  }),

  // ── Arbeit & Einkommen ──────────────────────────────────────────
  mastercase({
    id: 'job_loss_unemployment',
    title: 'Kündigung & Arbeitslosigkeit',
    domain: 'private',
    category: 'Arbeit & Einkommen',
    priority: 'mvp',
    journeyId: 'job_loss_unemployment',
    triggerPhrases: ['gekündigt', 'kündigung', 'arbeitslos', 'arbeitslosmeldung', 'job verloren'],
    userIntentExamples: ['Ich wurde gekündigt. Was muss ich tun?'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Agentur für Arbeit', 'Krankenkasse', 'Arbeitgeber', 'ggf. Jobcenter'],
    orderedActions: [
      action('Arbeitsuchend melden', 'Agentur für Arbeit', { status: 'required', sourceRequirement: 'verified', officialActionId: 'register_jobseeker', timing: 'rechtzeitig vor Ende' }),
      action('Arbeitslos melden', 'Agentur für Arbeit', { status: 'required', sourceRequirement: 'verified', officialActionId: 'register_unemployed' }),
      action('Arbeitslosengeld klären', 'Agentur für Arbeit', { status: 'conditional', sourceRequirement: 'verified', officialActionId: 'alg1_apply' }),
      action('Krankenversicherung / Übergang prüfen', 'Krankenkasse', { status: 'required', sourceRequirement: 'missing' }),
      action('Weiterbildung besprechen', 'Agentur für Arbeit', { status: 'optional', sourceRequirement: 'verified', officialActionId: 'training_counselling' }),
      action('Bürgergeld optional prüfen', 'Jobcenter', { status: 'conditional', sourceRequirement: 'missing', officialActionId: 'buergergeld_housing', notes: 'Nur wenn relevant — kein Anspruch versprechen' }),
    ],
    requiredDocuments: ['Kündigungsschreiben', 'Arbeitsvertrag', 'Lohnabrechnungen', 'Ausweis'],
    optionalDocuments: ['Lebenslauf', 'Qualifikationsnachweise'],
    officialActionIds: ['register_jobseeker', 'register_unemployed', 'alg1_apply', 'training_counselling', 'buergergeld_housing', 'sick_note_report'],
    regionalLookupRequired: false,
    sourceStatus: 'verified_catalog',
    missingQuestions: ['Wann endet das Arbeitsverhältnis?', 'Liegt ein Kündigungsschreiben vor?'],
    safetyNotes: ['Keine Leistungszusage — zuständige Stelle entscheidet.'],
    testInputs: ['Ich wurde gekündigt. Was muss ich tun?'],
  }),
  mastercase({
    id: 'sickness_during_employment_or_jobloss',
    title: 'Krankheit bei Kündigung / Arbeitslosigkeit',
    domain: 'private',
    category: 'Arbeit & Einkommen',
    priority: 'mvp',
    journeyId: 'job_loss_unemployment',
    triggerPhrases: ['krankgeschrieben', 'arbeitsunfähig', 'krank und gekündigt', 'krankschreibung'],
    userIntentExamples: ['Ich wurde gekündigt und bin krankgeschrieben.'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Arbeitgeber', 'Krankenkasse', 'Agentur für Arbeit'],
    orderedActions: [
      action('Arbeitsunfähigkeit ärztlich klären', 'Arzt', { status: 'required', sourceRequirement: 'template' }),
      action('Meldepflichten Arbeitgeber / Kasse / Agentur trennen', 'Arbeitgeber / Krankenkasse / Agentur für Arbeit', { status: 'required', sourceRequirement: 'template', officialActionId: 'sick_note_report' }),
      action('Arbeitslosmeldung vorbereiten', 'Agentur für Arbeit', { status: 'conditional', sourceRequirement: 'verified', officialActionId: 'register_unemployed' }),
    ],
    requiredDocuments: ['AU-Bescheinigung', 'Kündigungsschreiben'],
    optionalDocuments: [],
    officialActionIds: ['sick_note_report', 'register_unemployed'],
    regionalLookupRequired: false,
    sourceStatus: 'verified_catalog',
    missingQuestions: ['Bist du aktuell arbeitsunfähig?'],
    safetyNotes: ['Keine Umgehungs- oder Betrugshinweise — nur neutrale Meldepflichten.'],
    governanceNotes: ['Wenn du tatsächlich arbeitsunfähig bist, kläre das ärztlich und halte Meldepflichten sauber getrennt.', ...GOVERNANCE_DEFAULT],
    testInputs: ['Ich wurde gekündigt und bin krankgeschrieben. Was muss ich tun?'],
  }),
  mastercase({
    id: 'unemployment_benefit',
    title: 'Arbeitslosengeld',
    domain: 'private',
    category: 'Arbeit & Einkommen',
    priority: 'mvp',
    journeyId: 'unemployment_training',
    triggerPhrases: ['arbeitslosengeld', 'alg1', 'alg i'],
    userIntentExamples: ['Wie beantrage ich Arbeitslosengeld?'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Agentur für Arbeit'],
    orderedActions: [
      action('Arbeitslos melden', 'Agentur für Arbeit', { status: 'required', sourceRequirement: 'verified', officialActionId: 'register_unemployed' }),
      action('Arbeitslosengeld klären', 'Agentur für Arbeit', { status: 'required', sourceRequirement: 'verified', officialActionId: 'alg1_apply' }),
    ],
    requiredDocuments: ['Kündigung', 'Arbeitsverträge', 'Lohnabrechnungen'],
    optionalDocuments: [],
    officialActionIds: ['register_unemployed', 'alg1_apply'],
    regionalLookupRequired: false,
    sourceStatus: 'verified_catalog',
    missingQuestions: ['Seit wann arbeitslos?'],
    safetyNotes: [],
    testInputs: ['Ich brauche Arbeitslosengeld.'],
  }),
  mastercase({
    id: 'citizen_benefit_basic_security',
    title: 'Bürgergeld / Grundsicherung',
    domain: 'private',
    category: 'Arbeit & Einkommen',
    priority: 'important',
    journeyId: 'unemployment_training',
    triggerPhrases: ['bürgergeld', 'grundsicherung', 'jobcenter', 'hartz'],
    userIntentExamples: ['Reicht mein Einkommen nicht — was ist mit Bürgergeld?'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Jobcenter'],
    orderedActions: [
      action('Leistungsweg beim Jobcenter klären', 'Jobcenter', { status: 'required', sourceRequirement: 'missing', officialActionId: 'buergergeld_housing', notes: 'Beratung — kein Anspruch versprechen' }),
    ],
    requiredDocuments: ['Einkommensnachweise', 'Mietvertrag', 'Kontoauszüge'],
    optionalDocuments: [],
    officialActionIds: ['buergergeld_housing'],
    regionalLookupRequired: true,
    sourceStatus: 'catalog_missing',
    missingQuestions: ['Bist du bereits beim Jobcenter gemeldet?'],
    safetyNotes: ['Clara verspricht keinen Leistungsanspruch.'],
    governanceNotes: ['Orientierung zur Prüfung — keine Zusage auf Bürgergeld oder Grundsicherung.', ...GOVERNANCE_DEFAULT],
    testInputs: ['Ich überlege Bürgergeld zu beantragen.'],
  }),
  mastercase({
    id: 'further_training_interest',
    title: 'Weiterbildung & Qualifizierung',
    domain: 'private',
    category: 'Arbeit & Einkommen',
    priority: 'mvp',
    journeyId: 'unemployment_training',
    triggerPhrases: ['weiterbildung', 'umschulung', 'bildungsgutschein', 'qualifizierung'],
    userIntentExamples: ['Ich möchte mich weiterbilden nach der Kündigung.'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Agentur für Arbeit'],
    orderedActions: [
      action('Beratung zur Weiterbildung', 'Agentur für Arbeit', { status: 'required', sourceRequirement: 'verified', officialActionId: 'training_counselling', notes: 'Bildungsgutschein — Prüfung durch Agentur erforderlich' }),
    ],
    requiredDocuments: ['Lebenslauf', 'Qualifikationsnachweise'],
    optionalDocuments: [],
    officialActionIds: ['training_counselling'],
    regionalLookupRequired: false,
    sourceStatus: 'verified_catalog',
    missingQuestions: ['Arbeitslos gemeldet oder noch angestellt?'],
    safetyNotes: ['Bildungsgutschein nur nach Beratung und Prüfung — kein Automatismus.'],
    testInputs: ['Ich will mich umschulen lassen.'],
  }),
  mastercase({
    id: 'income_not_enough',
    title: 'Einkommen reicht nicht',
    domain: 'private',
    category: 'Arbeit & Einkommen',
    priority: 'important',
    journeyId: 'housing_support',
    triggerPhrases: ['einkommen nicht genug', 'geld reicht nicht', 'finanzielle not'],
    userIntentExamples: ['Mein Gehalt reicht nicht für die Lebenshaltungskosten.'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Wohngeldstelle', 'Jobcenter', 'Familienkasse'],
    orderedActions: [
      action('Wohngeld prüfen', 'Wohngeldstelle', { status: 'required', sourceRequirement: 'verified', officialActionId: 'wohngeld_apply' }),
      action('Kinderzuschlag optional', 'Familienkasse', { status: 'conditional', sourceRequirement: 'verified', officialActionId: 'kinderzuschlag_check' }),
      action('Bürgergeld optional prüfen', 'Jobcenter', { status: 'conditional', sourceRequirement: 'missing', officialActionId: 'buergergeld_housing' }),
    ],
    requiredDocuments: ['Einkommensnachweise', 'Mietvertrag'],
    optionalDocuments: [],
    officialActionIds: ['wohngeld_apply', 'kinderzuschlag_check', 'buergergeld_housing'],
    regionalLookupRequired: true,
    sourceStatus: 'verified_catalog',
    missingQuestions: ['Wohnkosten oder allgemeines Einkommen?'],
    safetyNotes: [],
    testInputs: ['Mein Einkommen reicht hinten und vorne nicht.'],
  }),

  // ── Gesundheit & Pflege ─────────────────────────────────────────
  mastercase({
    id: 'care_case_family_member',
    title: 'Pflegefall in der Familie',
    domain: 'private',
    category: 'Gesundheit & Pflege',
    priority: 'mvp',
    journeyId: 'family_care',
    triggerPhrases: ['pflegefall', 'angehörige pflege', 'pflegebedürftig'],
    userIntentExamples: ['In meiner Familie gibt es einen Pflegefall.'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Pflegekasse', 'Pflegestützpunkt', 'Sozialamt Kirkel'],
    orderedActions: [
      action('Pflegebedarf einordnen', 'Pflegestützpunkt', { status: 'required', sourceRequirement: 'regional', officialActionId: 'care_counselling' }),
      action('Pflegegrad-Antrag vorbereiten', 'Pflegekasse', { status: 'required', sourceRequirement: 'verified', officialActionId: 'care_grade_apply' }),
      action('Entlastungsleistungen prüfen', 'Pflegekasse', { status: 'optional', sourceRequirement: 'verified', officialActionId: 'relief_benefits' }),
    ],
    requiredDocuments: ['Versichertennachweis', 'Atteste'],
    optionalDocuments: ['Vollmacht'],
    officialActionIds: ['care_counselling', 'care_grade_apply', 'relief_benefits'],
    regionalLookupRequired: true,
    sourceStatus: 'verified_catalog',
    missingQuestions: ['Pflege zu Hause oder in Einrichtung?'],
    safetyNotes: [],
    testInputs: ['Pflegefall in der Familie — welche Leistungen gibt es?'],
  }),
  mastercase({
    id: 'care_level_application',
    title: 'Pflegegrad beantragen',
    domain: 'private',
    category: 'Gesundheit & Pflege',
    priority: 'mvp',
    journeyId: 'family_care',
    triggerPhrases: ['pflegegrad', 'mdk', 'pflegegrad antrag'],
    userIntentExamples: ['Wie beantrage ich einen Pflegegrad?'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Pflegekasse'],
    orderedActions: [
      action('Pflegegrad-Antrag stellen', 'Pflegekasse', { status: 'required', sourceRequirement: 'verified', officialActionId: 'care_grade_apply' }),
      action('Beratung nutzen', 'Pflegestützpunkt', { status: 'advisory', sourceRequirement: 'regional', officialActionId: 'care_counselling' }),
    ],
    requiredDocuments: ['Versichertennachweis', 'Atteste'],
    optionalDocuments: [],
    officialActionIds: ['care_grade_apply', 'care_counselling'],
    regionalLookupRequired: true,
    sourceStatus: 'verified_catalog',
    missingQuestions: ['Liegt bereits ein Pflegegrad vor?'],
    safetyNotes: [],
    testInputs: ['Ich brauche einen Pflegegrad für meine Mutter.'],
  }),
  mastercase({
    id: 'disability_or_severe_disability',
    title: 'Schwerbehinderung / Nachteilsausgleich',
    domain: 'private',
    category: 'Gesundheit & Pflege',
    priority: 'later',
    triggerPhrases: ['schwerbehinderung', 'behinderung', 'gd behindertenausweis'],
    userIntentExamples: ['Wie beantrage ich einen Schwerbehindertenausweis?'],
    knownContextUsage: ['municipality', 'federalState'],
    responsibleAuthorities: ['Versorgungsamt', 'Integrationsamt'],
    orderedActions: [
      action('Antrag und Nachweise vorbereiten', 'Versorgungsamt', { status: 'required', sourceRequirement: 'regional', notes: 'Zuständige Stelle suchen' }),
    ],
    requiredDocuments: ['Atteste', 'Ausweis'],
    optionalDocuments: [],
    officialActionIds: [],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: ['Liegt eine Diagnose vor?'],
    safetyNotes: [],
    testInputs: ['Ich möchte Schwerbehindertenausweis beantragen.'],
  }),
  mastercase({
    id: 'health_insurance_transition',
    title: 'Krankenversicherung wechseln',
    domain: 'private',
    category: 'Gesundheit & Pflege',
    priority: 'important',
    journeyId: 'job_loss_unemployment',
    triggerPhrases: ['krankenversicherung wechseln', 'krankenkasse wechseln', 'versicherung nach kündigung'],
    userIntentExamples: ['Was passiert mit meiner Krankenversicherung nach der Kündigung?'],
    knownContextUsage: KIRKEL_CTX,
    responsibleAuthorities: ['Krankenkasse', 'Agentur für Arbeit'],
    orderedActions: [
      action('Versicherungsstatus prüfen', 'Krankenkasse', { status: 'required', sourceRequirement: 'missing' }),
      action('Arbeitslosmeldung koordinieren', 'Agentur für Arbeit', { status: 'conditional', sourceRequirement: 'verified', officialActionId: 'register_unemployed' }),
    ],
    requiredDocuments: ['Versichertennachweis', 'Kündigung'],
    optionalDocuments: [],
    officialActionIds: ['register_unemployed'],
    regionalLookupRequired: false,
    sourceStatus: 'catalog_missing',
    missingQuestions: ['Noch angestellt oder bereits arbeitslos?'],
    safetyNotes: [],
    testInputs: ['Nach der Kündigung — welche Krankenversicherung?'],
  }),

  // ── Tod & Nachlass ──────────────────────────────────────────────
  mastercase({
    id: 'death_in_family',
    title: 'Todesfall in der Familie',
    domain: 'private',
    category: 'Tod & Nachlass',
    priority: 'mvp',
    journeyId: 'death_case',
    triggerPhrases: ['todesfall', 'sterbefall', 'verstorben', 'beerdigung'],
    userIntentExamples: ['Ein Angehöriger ist gestorben — was muss ich tun?'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Standesamt Kirkel', 'Versicherungen', 'Nachlassgericht (Orientierung)'],
    orderedActions: [
      action('Sterbeurkunde beim Standesamt', 'Standesamt Kirkel', { status: 'required', sourceRequirement: 'regional', officialActionId: 'death_register', notes: 'Behutsam — erste behördliche Schritte' }),
      action('Versicherungen informieren', 'Versicherungen', { status: 'required', sourceRequirement: 'template', officialActionId: 'insurance_inform_death' }),
      action('Hinterbliebenenrente optional klären', 'Deutsche Rentenversicherung', { status: 'optional', sourceRequirement: 'missing', officialActionId: 'survivor_pension' }),
      action('Nachlass / Erbschaft Orientierung', 'Nachlassgericht (Orientierung)', { status: 'advisory', sourceRequirement: 'template', officialActionId: 'probate_orientation' }),
    ],
    requiredDocuments: ['Sterbeurkunde', 'Ausweis'],
    optionalDocuments: ['Testament'],
    officialActionIds: ['death_register', 'insurance_inform_death', 'survivor_pension', 'probate_orientation'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: ['Gibt es ein Testament oder Erben?'],
    safetyNotes: ['Behutsame Sprache — kein Zeitdruck, keine Rechtsberatung zum Erbrecht.'],
    testInputs: ['Mein Vater ist gestorben. Was muss ich jetzt erledigen?'],
  }),
  mastercase({
    id: 'death_certificate',
    title: 'Sterbeurkunde',
    domain: 'private',
    category: 'Tod & Nachlass',
    priority: 'important',
    journeyId: 'death_case',
    triggerPhrases: ['sterbeurkunde', 'totenbeschau', 'standesamt todesfall'],
    userIntentExamples: ['Wo bekomme ich die Sterbeurkunde?'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Standesamt Kirkel'],
    orderedActions: [
      action('Sterbeurkunde beantragen', 'Standesamt Kirkel', { status: 'required', sourceRequirement: 'regional', officialActionId: 'death_register' }),
    ],
    requiredDocuments: ['Ausweis'],
    optionalDocuments: [],
    officialActionIds: ['death_register'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: [],
    safetyNotes: ['Behutsame Kommunikation.'],
    testInputs: ['Ich brauche eine Sterbeurkunde.'],
  }),
  mastercase({
    id: 'pension_after_death',
    title: 'Hinterbliebenenrente',
    domain: 'private',
    category: 'Tod & Nachlass',
    priority: 'important',
    journeyId: 'death_case',
    triggerPhrases: ['hinterbliebenenrente', 'witwenrente', 'witwerrente'],
    userIntentExamples: ['Steht mir nach dem Tod meines Partners eine Rente zu?'],
    knownContextUsage: ['federalState'],
    responsibleAuthorities: ['Deutsche Rentenversicherung'],
    orderedActions: [
      action('Hinterbliebenenleistungen prüfen', 'Deutsche Rentenversicherung', { status: 'required', sourceRequirement: 'missing', officialActionId: 'survivor_pension' }),
    ],
    requiredDocuments: ['Sterbeurkunde', 'Eheurkunde', 'Rentenversicherungsnummer'],
    optionalDocuments: [],
    officialActionIds: ['survivor_pension'],
    regionalLookupRequired: false,
    sourceStatus: 'catalog_missing',
    missingQuestions: ['War die Person verheiratet oder geschieden?'],
    safetyNotes: ['Keine Anspruchszusage.'],
    testInputs: ['Nach dem Tod meines Mannes — Rentenansprüche?'],
  }),
  mastercase({
    id: 'inheritance_court_orientation',
    title: 'Erbschaft & Nachlassgericht',
    domain: 'private',
    category: 'Tod & Nachlass',
    priority: 'later',
    journeyId: 'death_case',
    triggerPhrases: ['erbschaft', 'nachlass', 'erben', 'testament'],
    userIntentExamples: ['Es gibt einen Nachlass — wo bekomme ich Orientierung?'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Nachlassgericht (Orientierung)', 'Notar (Orientierung)'],
    orderedActions: [
      action('Nachlass Orientierung', 'Nachlassgericht (Orientierung)', { status: 'advisory', sourceRequirement: 'template', officialActionId: 'probate_orientation' }),
    ],
    requiredDocuments: ['Sterbeurkunde', 'Testament falls vorhanden'],
    optionalDocuments: [],
    officialActionIds: ['probate_orientation'],
    regionalLookupRequired: true,
    sourceStatus: 'template_only',
    missingQuestions: ['Gibt es ein Testament?'],
    safetyNotes: ['Keine Rechtsberatung zum Erbrecht.'],
    testInputs: ['Es gibt einen Nachlass zu regeln.'],
  }),
  mastercase({
    id: 'insurance_notifications',
    title: 'Versicherungen nach Todesfall',
    domain: 'private',
    category: 'Tod & Nachlass',
    priority: 'important',
    journeyId: 'death_case',
    triggerPhrases: ['versicherung todesfall', 'versicherungen informieren'],
    userIntentExamples: ['Welche Versicherungen muss ich nach einem Todesfall informieren?'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Versicherungen', 'Krankenkasse', 'Rentenversicherung'],
    orderedActions: [
      action('Versicherungen und Verträge informieren', 'Versicherungen', { status: 'required', sourceRequirement: 'template', officialActionId: 'insurance_inform_death' }),
    ],
    requiredDocuments: ['Sterbeurkunde', 'Versicherungspolicen'],
    optionalDocuments: [],
    officialActionIds: ['insurance_inform_death'],
    regionalLookupRequired: false,
    sourceStatus: 'template_only',
    missingQuestions: [],
    safetyNotes: [],
    testInputs: ['Nach dem Todesfall — welche Versicherungen melden?'],
  }),

  // ── Identität & Dokumente ───────────────────────────────────────
  mastercase({
    id: 'id_card_renewal',
    title: 'Personalausweis',
    domain: 'private',
    category: 'Identität & Dokumente',
    priority: 'mvp',
    journeyId: 'id_passport',
    triggerPhrases: ['personalausweis', 'ausweis beantragen', 'ausweis abgelaufen'],
    userIntentExamples: ['Ich brauche einen neuen Personalausweis.'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Bürgeramt Kirkel'],
    orderedActions: [
      action('Personalausweis beantragen', 'Bürgeramt Kirkel', { status: 'required', sourceRequirement: 'regional', officialActionId: 'id_card_apply' }),
    ],
    requiredDocuments: ['Biometrisches Foto', 'Alter Ausweis'],
    optionalDocuments: ['Geburtsurkunde'],
    officialActionIds: ['id_card_apply'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: ['Erstausstellung oder Verlängerung?'],
    safetyNotes: [],
    testInputs: ['Ich brauche einen Personalausweis beim Bürgeramt.'],
  }),
  mastercase({
    id: 'passport_adult',
    title: 'Reisepass (Erwachsene)',
    domain: 'private',
    category: 'Identität & Dokumente',
    priority: 'mvp',
    journeyId: 'id_passport',
    triggerPhrases: ['reisepass', 'pass beantragen'],
    userIntentExamples: ['Ich brauche einen Reisepass.'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Bürgeramt Kirkel'],
    orderedActions: [
      action('Reisepass beantragen', 'Bürgeramt Kirkel', { status: 'required', sourceRequirement: 'regional', officialActionId: 'passport_apply' }),
    ],
    requiredDocuments: ['Biometrisches Foto', 'Alter Pass oder Ausweis'],
    optionalDocuments: [],
    officialActionIds: ['passport_apply'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: [],
    safetyNotes: [],
    testInputs: ['Ich möchte einen Reisepass beantragen.'],
  }),
  mastercase({
    id: 'passport_child',
    title: 'Reisepass (Kind)',
    domain: 'private',
    category: 'Identität & Dokumente',
    priority: 'important',
    journeyId: 'id_passport',
    triggerPhrases: ['kind reisepass', 'pass für kind'],
    userIntentExamples: ['Mein Kind braucht einen Reisepass.'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Bürgeramt Kirkel'],
    orderedActions: [
      action('Kinderreisepass beantragen', 'Bürgeramt Kirkel', { status: 'required', sourceRequirement: 'regional', officialActionId: 'passport_apply' }),
    ],
    requiredDocuments: ['Biometrisches Foto', 'Ausweis der Sorgeberechtigten', 'Geburtsurkunde'],
    optionalDocuments: [],
    officialActionIds: ['passport_apply'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: ['Einverständnis beider Sorgeberechtigter?'],
    safetyNotes: [],
    testInputs: ['Reisepass für mein Kind beantragen.'],
  }),
  mastercase({
    id: 'name_change_after_marriage',
    title: 'Namensänderung nach Heirat',
    domain: 'private',
    category: 'Identität & Dokumente',
    priority: 'mvp',
    journeyId: 'marriage_name_change',
    triggerPhrases: ['namensänderung', 'heirat', 'name ändern nach hochzeit'],
    userIntentExamples: ['Nach der Heirat möchte ich meinen Namen ändern.'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Standesamt Kirkel', 'Bürgeramt Kirkel'],
    orderedActions: [
      action('Eheschließung / Heirat vorbereiten', 'Standesamt Kirkel', { status: 'required', sourceRequirement: 'regional', officialActionId: 'marriage_register' }),
      action('Namensänderung und Ausweis aktualisieren', 'Bürgeramt Kirkel', { status: 'required', sourceRequirement: 'regional', officialActionId: 'name_change_id' }),
    ],
    requiredDocuments: ['Ausweis', 'Geburtsurkunde', 'Heiratsurkunde'],
    optionalDocuments: [],
    officialActionIds: ['marriage_register', 'name_change_id'],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: ['Ist die Heirat bereits erfolgt?'],
    safetyNotes: [],
    testInputs: ['Nach der Hochzeit Namen im Ausweis ändern.'],
  }),
  mastercase({
    id: 'certificate_request',
    title: 'Urkunden & Bescheinigungen',
    domain: 'private',
    category: 'Identität & Dokumente',
    priority: 'later',
    triggerPhrases: ['urkunde', 'bescheinigung', 'beglaubigung', 'geburtsurkunde nachbestellen'],
    userIntentExamples: ['Ich brauche eine beglaubigte Urkunde.'],
    knownContextUsage: ['municipality'],
    responsibleAuthorities: ['Standesamt Kirkel', 'Bürgeramt Kirkel'],
    orderedActions: [
      action('Urkunde / Bescheinigung beantragen', 'Standesamt / Bürgeramt Kirkel', { status: 'required', sourceRequirement: 'regional', notes: 'Zuständige Stelle suchen' }),
    ],
    requiredDocuments: ['Ausweis'],
    optionalDocuments: [],
    officialActionIds: [],
    regionalLookupRequired: true,
    sourceStatus: 'regional_lookup_required',
    missingQuestions: ['Welche Urkunde wird benötigt?'],
    safetyNotes: [],
    testInputs: ['Ich brauche eine Geburtsurkunde Nachbestellung.'],
  }),

  // ── Rente ───────────────────────────────────────────────────────
  mastercase({
    id: 'retirement_application',
    title: 'Rentenantrag',
    domain: 'private',
    category: 'Rente',
    priority: 'mvp',
    journeyId: 'pension_retirement',
    triggerPhrases: ['rente beantragen', 'rentenantrag', 'ruhestand'],
    userIntentExamples: ['Ich gehe in Rente — was muss ich beantragen?'],
    knownContextUsage: ['federalState'],
    responsibleAuthorities: ['Deutsche Rentenversicherung', 'Krankenkasse'],
    orderedActions: [
      action('Rentenantrag vorbereiten', 'Deutsche Rentenversicherung', { status: 'required', sourceRequirement: 'missing', officialActionId: 'pension_apply' }),
      action('Krankenversicherung im Ruhestand klären', 'Krankenkasse', { status: 'required', sourceRequirement: 'missing', officialActionId: 'health_insurance_retirement' }),
    ],
    requiredDocuments: ['Versicherungsverlauf', 'Ausweis'],
    optionalDocuments: ['Bescheide'],
    officialActionIds: ['pension_apply', 'health_insurance_retirement'],
    regionalLookupRequired: false,
    sourceStatus: 'catalog_missing',
    missingQuestions: ['Wann ist der geplante Rentenbeginn?'],
    safetyNotes: [],
    testInputs: ['Ich möchte meine Rente beantragen.'],
  }),
  mastercase({
    id: 'pension_record_check',
    title: 'Renteninformation prüfen',
    domain: 'private',
    category: 'Rente',
    priority: 'important',
    journeyId: 'pension_retirement',
    triggerPhrases: ['renteninformation', 'rentenkonto', 'versicherungsverlauf'],
    userIntentExamples: ['Ich möchte meine Rentenansprüche prüfen.'],
    knownContextUsage: ['federalState'],
    responsibleAuthorities: ['Deutsche Rentenversicherung'],
    orderedActions: [
      action('Renteninformation anfordern', 'Deutsche Rentenversicherung', { status: 'required', sourceRequirement: 'missing', officialActionId: 'pension_apply', notes: 'Kontoauszug der Rentenversicherung' }),
    ],
    requiredDocuments: ['Ausweis'],
    optionalDocuments: [],
    officialActionIds: ['pension_apply'],
    regionalLookupRequired: false,
    sourceStatus: 'catalog_missing',
    missingQuestions: [],
    safetyNotes: [],
    testInputs: ['Wie prüfe ich meinen Rentenversicherungsverlauf?'],
  }),
];
